### ISSUE TITLE
Add step-by-step formatting to WordPress

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/cannabis.ca.gov#107]
After final content is imported into WordPress, add step-by-step formatting to all pages that need it. These are noted in Airtable.

**Comment by m-sullivan7** [comment]
@kkoryaka This is the design that the cannabis team would like to implement on a few different pages. Do you need anything else to do this work?

<img width="632" alt="Screen Shot 2021-06-18 at 12 10 26 PM" src="https://user-images.githubusercontent.com/69169190/122609066-37eaa980-d032-11eb-83d4-84973673d938.png">

When you're finished, my task (the original purpose of the ticket) will be to implement the block on the appropriate pages.

**Comment by abquirarte** [comment]
FWIW it would be an iteration from how we did the steps in alpha:
https://alpha.ca.gov/hire-licensed-contractor-home-improvements/

Angelica Quirarte, "Angie"
Deputy Director | Office of Digital Innovation
c: 916-526-5510 or 916-812-6864
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>

**Comment by m-sullivan7** [comment]
Step-by-step list added to the following pages:

- [About the Department of Cannabis Control](https://staginginye.prod3.sites.ca.gov/about-us/about-dcc/)
- [How to apply for or renew a license](https://staginginye.prod3.sites.ca.gov/applicants/how-to-apply-renew/)
- [Medicinal cannabis](https://staginginye.prod3.sites.ca.gov/consumers/medicinal-cannabis/)
- [Banking and insurance](https://staginginye.prod3.sites.ca.gov/resources/banking-insurance/)
- [Disaster relief programs](https://staginginye.prod3.sites.ca.gov/resources/disaster-relief-programs/)

All pages that needed the step-by-step formatting now have it.
