### ISSUE TITLE
Component: Search Bar (serp path?)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#119]
Is there a short code or do we need to enable a plugin? Need to create page container.

**Comment by aaronhans** [comment]
Right now the SERP path is /serp/ with the query as a url parameter: https://staginginye.prod3.sites.ca.gov/serp/?q=cannabis

We are using a legacy google site search widget. You can't sign up for this service anymore but google has grandfathered all CA state sites in and continues to support the service for us.

The google site search widget uses the public index and returns results similar to limiting a query by site:yourdomain

The search results are retrieved with a client side xhr call after the initial page renders. Some customization can be done via CSS overrides, the url and page around the SERP are controlled in wordpress/site theme

**Comment by aaronhans** [comment]
@wrendo could you be more specific about what we need here? We didn't design this page or show it to stakeholders so maybe going with the default for initial launch is ok
