### ISSUE TITLE
Content: Hero block content

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#120]
Do we know what copy content will be featured? I'm waiting on new pics from Christina

![Screen Shot 2021-06-20 at 12 01 45 PM](https://user-images.githubusercontent.com/1387973/122687208-16242a80-d1ca-11eb-88a3-67d5856ef9d6.png)

**Comment by m-sullivan7** [comment]
I haven't heard from Christina. Good catch!

**Comment by wrendo** [comment]
Here's a folder link to pics we can use for the hero block: https://drive.google.com/drive/folders/1ljmhmhQK6rbcoL8GFVz6KAek70ZW5oAR?usp=sharing

Their preference is: https://drive.google.com/file/d/1ccrz6eImlIihWwBW2zURY9p9fC3FhGwx/view?usp=sharing

**Comment by m-sullivan7** [comment]
I updated the hero image on the homepage with the preferred image. 😄

**Comment by m-sullivan7** [comment]
Christina provided new copy (including button link) for the hero block. This is [updated on production](https://staginginye.prod3.sites.ca.gov/) and this ticket is done.
