### ISSUE TITLE
Bug: Search bar animation issue

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#121]
Noticing the same search bar animation glitch whenever clicking on the header logo to go back to the home screen
![Screen Shot 2021-06-20 at 12 03 13 PM (2)](https://user-images.githubusercontent.com/1387973/122687293-85018380-d1ca-11eb-9a6e-28a24654e207.png)

**Comment by kkoryaka** [comment]
Unfortunately that is not fixable at this point because it picking up the css styles sequentially and for the fragment of the second the template's css will be applied to the search box before manual css takes over.
