### ISSUE TITLE
Shorten menu title to DCC events

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#125]
The menu title for Department of Cannabis Control events can probably be shortened to DCC events. We can run that by Christina. Non-critical

**Comment by m-sullivan7** [comment]
Agreed.

**Comment by m-sullivan7** [comment]
I do not know how to create a separate menu title for a page (or if it's possible). I'll need some guidance from an engineer. As this is a low priority ticket, I won't push it at the moment.

**Comment by m-sullivan7** [comment]
Chach updated the DCC events and About DCC pages to have those menu titles. This work is done in an area that editors can't get to. We'll either need CDT to open this up to them or provide some details on how to self-serve. Luckily, this isn't a launch concern. This ticket is done.
