### ISSUE TITLE
Content Bug: H3 headers showing in index

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/cannabis.ca.gov#129]
Example: On the [License types](https://staginginye.prod3.sites.ca.gov/applicants/license-types/) page, H3s are showing up in the left side navigation. Examples include:

- Determining your license type
- Type 7: volatile solvent manufacturing
- Type 6: non-volatile solvent manufacturing or mechanical extraction
- Type N: infusion of products
- Type P: packaging and labeling
- Type S: manufacturers who work in a shared-use facility
- Type 11: distributor
- Type 13: transport-only distributor
- Type 9: non-storefront retailer (delivery only)
- Type 10: storefront retailer

This issue may affect more than this page.

**Comment by m-sullivan7** [comment]
@adam-little Are the headers sized correctly according to the design? The H3s seem like they might be large, but maybe it's just me. 😄

**Comment by chachasikes** [comment]
Have this in a pre-release will be available in next update. Preview on dev.
