### ISSUE TITLE
Cosmetic: Typography

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#132]
**Size and weight**
- Please see [text styles in Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=127%3A789) for font sizes and weights

**Line height**

- Line height is 1.6 x font size.
- Note that in Figma I am not following this rule precisely because I am rounding to the nearest px size. 

**Paragraph spacing**

- Space between paragraphs should equal the height of one line of text.
- Space between list items should equal 0.5 height line of text.

**Spacing for headers**
Headings should be closer to the text they introduce than the text that precedes them.
- As a rule of thumb, use at least 1.5 times the amount of whitespace above the heading as below it.
- In Figma, I am using 48px above headers and 24px below them. But ideally this can be proportionate to the size of the header text.

**Indentation**
- ~~Lists should have a slight indentation. I don't have a specific measurement for this because Figma does not support it, but please increase slightly from what's on the production site.~~ [Done]
- ~~On lists, the entire list item should be indented, not just the first line of text.~~ [Done]

**Header fonts**
- ~~On [License Types](https://staginginye.prod3.sites.ca.gov/applicants/license-types/) page, h2 and h3 are the same size. In Figma, we are using 32px for H2 and 28px for H3~~ [Done]

**Links**

- ~~Please make inline text links underline~~ [Done]

**Comment by adam-little** [comment]
@kkoryaka Chach had completed some of these, but then her changes were overridden by your styles. Can you confirm that the following typography rules are applied? Especially around line height, header spacing, and link underlines?

**Comment by adam-little** [comment]
@timothyshambra @chachasikes I have updated the description in this issue as well as the Desktop and Mobile font sizes which you can view in the Text Styles board in Figma: https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=0%3A1

**Comment by chachasikes** [comment]
Assigning to @wrendo to review. 
If still not aligned, should be assigned to Konstantin.
