### ISSUE TITLE
Cosmetic: Drop down menu formatting on desktop

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#133]
In addition to [this issue about drop down appearing behind page content](https://github.com/cagov/cannabis.ca.gov/issues/130), here are some other menu related formatting issues:

01. There are overlapping grey lines at the top of the selected tab:

![image](https://user-images.githubusercontent.com/69167298/122823814-d171bf80-d2ad-11eb-9f72-5fbdf9fded9e.png)

02. Select state border is not fully visible: 

![image](https://user-images.githubusercontent.com/69167298/122823905-eb130700-d2ad-11eb-99e8-8d254073eb5c.png)

03. The color change on hover only appears for subpages. It does not appear for top level menu items.

**Comment by wrendo** [comment]
Not on Safari (ignore)
