### ISSUE TITLE
Bug: Resources slug

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/cannabis.ca.gov#134]
The page _Application resources_ page has the slug /applicants/resources. It appears to also be sitting on the slug /resources/. This makes the URL for all the pages in the _Resources_ section use the slug /resources-2/. The _Resources_ section should just be /resources/. If this means we need to rename the slug for _Application resources_, let's use /applicants/application-resources to mirror the page title.

**Comment by chachasikes** [comment]
Resolved on prod. Thanks for the heads up.

**Comment by m-sullivan7** [comment]
All good on my end! I'm going to move to done. :)
