### ISSUE TITLE
Cosmetic: Button grid sizing

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#138]
The buttons in the button grid are rather large. 

![Screen Shot 2021-06-21 at 6 01 35 PM](https://user-images.githubusercontent.com/1387973/122846553-ef91ec80-d2ba-11eb-864b-44de7739ada7.png)

**Comment by aaronhans** [comment]
This is a Safari specific bug which can be fixed by applying max height to the svg. I added this to production custom css, will put it into the plugin in upcoming PR

**Comment by aaronhans** [comment]
PR https://github.com/cagov/ca-design-system-gutenberg-blocks/pull/34
