### ISSUE TITLE
Cosmetic: Requirements for Cannabis Goods Page - Remove [H4] tag

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#140]
see screenshot
![H4](https://user-images.githubusercontent.com/1387973/122958587-bfd4fa00-d337-11eb-945f-925d4b2cb3b1.png)
1

**Comment by m-sullivan7** [comment]
I picked this up during my QA work yesterday. It's [already been fixed](https://staginginye.prod3.sites.ca.gov/licensees/requirements-cannabis-goods/#cannabis-concentrates). Moving this ticket to done.
