### ISSUE TITLE
Cosmetic: Access the License Portal Page - Put FAQ into Accordian

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#141]
see screenshot

![Screen Shot 2021-06-22 at 8 58 41 AM](https://user-images.githubusercontent.com/1387973/122960444-42f65000-d338-11eb-94bb-a29d384dd0fa.png)

**Comment by m-sullivan7** [comment]
This has been [fixed on prod](https://staginginye.prod3.sites.ca.gov/applicants/access-license-portals/#questions-and-answers).
