### ISSUE TITLE
Content: Page alert content

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#143]
For soft launch, we want it to say something like "Welcome to the soft launch! We welcome your feedback and would love to hear from you." or something better that will prompt them to use Ethnio or the feedback spreadsheet Christina will be distributing to her team.

For hard launch, we won't have any page alert initially, so having that off would be fine. Just need to train her team to create page alerts which I'm assuming is happening through the editor?

**Comment by m-sullivan7** [comment]
On production, we're not displaying a page alert on the homepage right now.

On the existing sites:
- The current cannabis.ca.gov does not have a page alert.
- BCC has a link to [Expedited Licensure for Refugees, Asylees, and Holders of Special Immigrant Visas](https://bcc.ca.gov/licensees/ab2113.html)
- No page alert on calcannabis.cdfa.ca.gov.
- No page alert on www.cdph.ca.gov/Programs/CEH/DFDCS/MCSB/Pages/MCSB.aspx.

**Comment by m-sullivan7** [comment]
Initial draft content provided by @wrendo : "Welcome to the soft launch! We welcome your feedback and would love to hear from you."

Revised content: "Welcome to the soft launch! We'd love to hear your thoughts. Provide them through the Ethnio survey here (it'll show up soon) or the spreadsheet Christina sent you."

**Comment by m-sullivan7** [comment]
Page alert added to the homepage. If Christina provides a link to the spreadsheet, we can add a link to the alert so people can go directly there. That said, what we've got should be an MVP.

OK to close @wrendo?

**Comment by m-sullivan7** [comment]
Removed text in parentheses per Ehb. Closing ticket as done.
