### ISSUE TITLE
Content: Missing DCC leadership names

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#153]
see screenshot

![Screen Shot 2021-06-23 at 8 42 18 AM](https://user-images.githubusercontent.com/1387973/123127421-1bb68600-d3ff-11eb-9e29-8edd96009bb9.png)

**Comment by m-sullivan7** [comment]
Christina said she is not sure if these will be announced prior to July 1. If they are not, we'll remove this section. @wrendo what would you like to set as the cut off date for getting the names?

**Comment by wrendo** [comment]
Per Christina, for each name simply put "To be announced"

**Comment by m-sullivan7** [comment]
[Page updated](https://staginginye.prod3.sites.ca.gov/about-us/about-dcc/) with _To be announced_ for each title. Closing ticket as done.
