### ISSUE TITLE
Cosmetic: All external site links should open new tabs

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#159]
Per audit spreadsheet. There's a separate issue for home page links assigned to Chach.

**Comment by m-sullivan7** [comment]
[Google Sheet](https://docs.google.com/spreadsheets/d/1QVq3KKQ60FxmGR8c5Eq60GW2FUfUUP8hxxUfT7QPtXE/edit?usp=sharing) created to note where external links are not opening in an external tab.

**Comment by m-sullivan7** [comment]
I've fixed the links were identified in yesterday's review session by the team. The only open items are the homepage links:

- The card links for _Search for a license_ and _File a complaint_ (I attempted to edit them like a normal link, but the block didn't allow me to do so)
- Social media links in the footer
- All state header and footer links

I'll need an engineer's help for these. (The last two may be as easy as telling me where in WordPress to edit them, or they may not.)
