### ISSUE TITLE
Design: Rethink dept header design layout (mobile)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#162]
see screenshot

![Department of Cannabis Control - Learn about California cannabis laws and licenses](https://user-images.githubusercontent.com/1387973/123132533-b2854180-d403-11eb-8597-9c83a7ee8b91.jpeg)

**Comment by adam-little** [comment]
I propose that we left-align the menu buttons. If we do this, then we should also switch the order so that the "Menu" button is closest to the edge of screen.

![image](https://user-images.githubusercontent.com/69167298/123172690-78d82900-d44b-11eb-99f3-4ab58e9a6843.png)
