### ISSUE TITLE
Design (or bug?): Non sticky header (mobile)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#164]
Header should probably stick or at least shrink and stick, so that the search bar and menu are accessible without having to scroll to the top of the page.

**Comment by adam-little** [comment]
Design recommendation was to reduce height and make header stick. On interior pages, the page nav would also become sticky.

We will have to revisit this now that the logo + agency title are all one graphic.

![image](https://user-images.githubusercontent.com/69167298/123170184-36f9b380-d448-11eb-89e2-fd76bd92e546.png)
![image](https://user-images.githubusercontent.com/69167298/123170146-2ba68800-d448-11eb-82ea-aae6da6e3fa7.png)

**Comment by adam-little** [comment]
Another way of providing quick access to site navigation is to show the header on reverse scroll. This ensures that the header is hidden whenever people are reading a page (moving down the screen) but becomes immediately available as someone begins to scroll towards the top.
