### ISSUE TITLE
Bug: Dept footer sign up link doesn't go to sign up page

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#176]
Clicking sign up link goes to...
![Screen Shot 2021-06-24 at 11 13 21 AM](https://user-images.githubusercontent.com/1387973/123312541-555dbe80-d4dd-11eb-8bc3-7aebd80ef9ad.png)
![Screen Shot 2021-06-24 at 11 14 02 AM](https://user-images.githubusercontent.com/1387973/123312542-55f65500-d4dd-11eb-8192-90b2636c620c.png)

**Comment by aaronhans** [comment]
fixed
