### ISSUE TITLE
Research: Ethnio strategy

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#184]
The Ethnio popup on mobile is super annoying when it happens on every page. We'll have to think through the intercept strategy in terms of where we want to strategically place it other than the homepage

**Comment by clarita1980** [comment]
Yes, intercept for now I think should only be on the homepage. 
Byron is in charge of this. I created and then gave him a seat and he now owns the intercept. He needs to make this adjustments. 
I also think it needs to be displayed on the right, not the left. This is more the common behavior for popups.
