### ISSUE TITLE
Cosmetic: Improve Back to Top button styling

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#186]
Anyway to have a lower profile button? Maybe just the up arrow?

**Comment by adam-little** [comment]
We typically try to pair icons with labels.

I think if we fix the scrolling behavior (which is not behaving as expected), that will address @wrendo's concern:
- When scrolling _down_ the page, the button should **not** be visible
- When a user researches the bottom of the page, the button becomes visible
- When scrolling _up_ the page, the button becomes visible
- When a user _stops_ scrolling up the page, the button should become hidden again

In summary: button is only visible when at the bottom of the page, or when scrolling up the page

In addition, here is visual design feedback:
- Per the design in Figma [see screenshot below], please remove right border and remove rounder corners on right side. Please also add dropshadow (#000 at 25% opacity, 4px blur)
![image](https://user-images.githubusercontent.com/69167298/123460830-4139c000-d5b6-11eb-9b4e-c83d547d03a8.png)

Lastly, I think the button should appear closer to the bottom of the screen:
- On mobile, there's too much space between the button and bottom of screen [see screenshot]. Can we decrease by about 50%?
- Same for desktop. On desktop, it would be great if the button aligned with the footer links when a user reaches the bottom of the page [see screenshot]

![image](https://user-images.githubusercontent.com/69167298/123461656-5b27d280-d5b7-11eb-9aad-634a70d59558.png)

![image](https://user-images.githubusercontent.com/69167298/123461127-abeafb80-d5b6-11eb-9316-8d41cdb8afeb.png)

**Comment by kkoryaka** [comment]
Updated back-to-top button position. Ans made it much smaller in mobile.

**Comment by adam-little** [comment]
This still does not address the recommended scrolling behavior, but I am going to close it for now.

I think we can revisit this when we have a larger discussion about "sticky" behaviors across the site (utility bar, nav, logo, page index, back to top).
