### ISSUE TITLE
Cosmetic: Alignment issue on Cultivation page

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#190]
The h1 and the rest of the page content are not aligned on the Cultivation page. 

It appears that this issue only effects this one page.

![image](https://user-images.githubusercontent.com/69167298/123475104-ebbade80-d5c8-11eb-8389-d73a1ade733a.png)

**Comment by chachasikes** [comment]
@adam-little  Is this still an issue? I see alignment.
