### ISSUE TITLE
Cannabis headless parity

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#192]
Building a headless WordPress version of the cannabis site means:
- We let authors write pages using the WordPress instance
- We retrieve the content from the WordPress API
- We build and deploy a statically generated site on every change

This provides the following benefits:
- We can address performance concerns
  - We don't have the WordPress plugin ecosystem adding code to the frontend
  - We can get the fastest possible time to first byte always because we are serving cached flat HTML files
- Production infrastructure is more robust
  - There is no production server scaling necessary because we are deploying flat files
  - We do not need to limit WordPress updates to maintenance windows or risk taking the live site offline if something goes wrong during a php plugin update. Since the frontend is fully decoupled it will continue to function on its own.
  - The WordPress instance will not receive visitor traffic. It could be secured behind firewall since it is only used for authoring

Goal:
Create a version of the homepage that retrieves live content from the production WordPress instance but is hosted on flat file host so we can show a clean performance comparison

Steps:
- [x] Pull the components Konstantin created for the header and footer
- [x] Pull the homepage content dynamically from the WordPress API
- [x] Integrate all components into new template
- [x] Collect and bundle necessary component styles and keep them in synch with design system
- [x] Unravel additional styles required from production locations
- [x] Review announcements module so it pulls data efficiently

Removed the following items in order to timebox this effort:

~~See if we can make performance improvements in twitter embed, Add appropriate tracking scripts for fair comparison, Include additional scripts like ethnio or disable them on production before performance tests, Perform side by side test using webpagetest video comparison~~

The headless version will be browseable at headless.cannabis.ca.gov, hopefully Koji and Art can help us advocate for it as a way to remove hassles like only patching production in maintenance windows

**Comment by aaronhans** [comment]
The following fixes have been made in the headless branch:
- [x] cards are wrong width
- [x] missing the fonts
- [x] menus are flipped in footer
- [x] needs a search results page
- [x] spacing on feature card header weird
- [x] search needs to submit to serp
- [x] announcements details page formatting off
- [x] search box color is different  
- [x] title on interior page is placed to right of content navigation (this is how it should be per figma)  
- [x] interior page with sidebar full content width too wide on mine
- [x] laws and regulations page I am missing button styles  
- [x] missing translations google widget
- [x] added breadcrumbs
- [x] feature card learn more button text not centered, some button styles missing 
- [x] mobile menu icon placement styles hosed
- [x] missing page 1 on announcements
- [x] mobile search does nothing, shows no search box
- [x] current page should be highlighted as bold in menu  
- [x] buckets and cloudfront cdn setup

following items still in progress to be completed by EOD 7/19:
- [ ] cname record ownership verification failed due to invalid record value, I pinpointed problem and notified CDT. When this is corrected, cert can be issued and headless.cannabis.ca.gov can be used
- [ ] social share icons oversized
- [ ] font weights are off even though same font is used with same weights. I think different woff files are being used, consult with Adam
- [ ] add nocrawl so search engines do not index headless version
- [ ] index.css.map missing error on internal pages

**Comment by aaronhans** [comment]
merged to main

**Comment by aaronhans** [comment]
Additional work will be done in subsequent tickets, moving this to done

**Comment by chachasikes** [comment]
Done, closing.
