### ISSUE TITLE
Cosmetic: Type - switch PM to AM (see screenshot)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#196]
![Screen Shot 2021-06-25 at 4 14 47 PM](https://user-images.githubusercontent.com/1387973/123493155-82d76480-d5d0-11eb-90ab-1c01c07a9818.png)

**Comment by m-sullivan7** [comment]
I wondered about the accuracy of this one when I saw it come through as I know some dispensaries that advertise 9:00-9:00 hours. Fixed. 👍
