### ISSUE TITLE
Accessibility: Some labels not translating

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#197]
see screenshots
![Screen Shot 2021-06-25 at 4 17 42 PM](https://user-images.githubusercontent.com/1387973/123493317-e95c8280-d5d0-11eb-9799-7bdc4374b106.png)
![Screen Shot 2021-06-25 at 4 17 51 PM](https://user-images.githubusercontent.com/1387973/123493319-e9f51900-d5d0-11eb-9619-b8d9398f52ab.png)

**Comment by chachasikes** [comment]
Interesting issue
cc @aaronhans 

Are these strings embedded in javascript behaviors?  If so, then google translate can't access them.

To make them translatable (in most cases), the markup needs to be on the page & not altered or replaced by any JS. Is that something we can do in the CAWeb Theme?

**Comment by kkoryaka** [comment]
Search placeholder is the only label that the google translate is able to translate. Search close button as well as back to top are the items that are generated in JavaScript or in CSS content property. My suggestion is to focus on the headless and make sure they are translated there.

**Comment by kkoryaka** [comment]
Those labels needs to be brought into HTML markup in the state template first and CAWeb team usually implements those changes right after State Template.

**Comment by chachasikes** [comment]
Done, closing.
