### ISSUE TITLE
Cosmetic: Typo Audit

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#198]
Again, a team effort to divide content pages amongst ourselves and give it a once over for typos. 

This is from events screen under Licensees:
![Screen Shot 2021-06-25 at 4 19 15 PM](https://user-images.githubusercontent.com/1387973/123493415-37718600-d5d1-11eb-8526-c7c3a61ed872.png)

This is from the first accordion in the Grants page:
![Screen Shot 2021-06-25 at 4 46 18 PM](https://user-images.githubusercontent.com/1387973/123494513-eebbcc00-d5d4-11eb-85c9-6e723b3ce48e.png)

**Comment by m-sullivan7** [comment]
[Google Sheet created](https://docs.google.com/spreadsheets/d/1QVq3KKQ60FxmGR8c5Eq60GW2FUfUUP8hxxUfT7QPtXE/edit?usp=sharing) for reviewing for typos.

**Comment by m-sullivan7** [comment]
All outstanding questions to Christina have been answered and incorporated as appropriate. Additionally, all content edits from her spreadsheet have been made. This is complete.
