### ISSUE TITLE
Content Bug: Missing index: Events page under Licensees

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#199]
see screenshot
![Screen Shot 2021-06-25 at 4 26 24 PM](https://user-images.githubusercontent.com/1387973/123493712-27a67180-d5d2-11eb-97be-0f71169f19a5.png)

**Comment by m-sullivan7** [comment]
Good catch! @chachasikes can content editors change the template a page is using or do we have to build this page again?

**Comment by m-sullivan7** [comment]
Changed the template thanks to Chach's helpful instructions. 😄
