### ISSUE TITLE
Content: Inconsistent text with "Track and Trace"

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#200]
![Screen Shot 2021-06-25 at 4 28 57 PM](https://user-images.githubusercontent.com/1387973/123493804-810ea080-d5d2-11eb-82d7-b36e6b06d2ae.png)

**Comment by m-sullivan7** [comment]
Excellent catch. Updated! I looked at four other pages that came up in a search for "Track and Trace" in WordPress and confirmed that the term is consistently capitalized on those pages as well.
