### ISSUE TITLE
Editor Bug: Move functionality is broken (post 7/1)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#201]
When you click on the 3 vertical dots and choose "Move to", it is unclear how the function actually works. It is fundamentally broken. User can still move blocks using the up and down arrows, but this is cumbersome if needing to move the block across many blocks.

Suggest disabling the menu option for now and just have the arrows as the main option until fix is available.

**Comment by chachasikes** [comment]
From some initial research, sounds like: move to is a keyboard accessibility feature & other people have complained about it. There isn't an obvious "off" switch, but when there is this kind of core UI bug, there is typically a long bug report thread with a few suggestions about mitigating the problem.

**Comment by chachasikes** [comment]
We can check what changed in WordPress 5.8 & see if this is improved at all, if not we can research complaints about this & if there are recommended improvements to this core feature of WordPress.

**Comment by chachasikes** [comment]
Support issue, don't think it's any better in WP 5.8

**Comment by chachasikes** [comment]
Adding this to QA backlog.
It this UI is still an issue, we may need to encourage some light WP editor training for WP using teams.
A video guide could be helpful - like "How to get proficient at Gutenberg blocks"

**Comment by chachasikes** [comment]
Closing but making note on this feedback for future efforts.
