### ISSUE TITLE
Editor UX: Hitting enter creates new block instead of new line (post 7/1)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#202]
User has to remember to hit shift-Enter to create a new line. This doesn't happen when creating paragraphs within columns.

**Comment by chachasikes** [comment]
This would be feedback for the accessible keyboard editor. 

There are some preview modes that highlight your active block, this could help with visual feedback for what context a user is in.

**Comment by chachasikes** [comment]
This is a support issue.

**Comment by chachasikes** [comment]
Closing - but making note for new work efforts.
