### ISSUE TITLE
Editor Bug: Column suggestion won't go away

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#205]
Deleting any created columns doesn't make the column suggestion go away. Not sure how to make it go away.

**Comment by chachasikes** [comment]
This is core WordPress & a training issue: you do need to select the column selector container before you can delete it.

There are some additional outline tools that editors can use.

Let's re-review with WordPress 5.8 before we propose improvements to see if they did any subtle changes with UI selection that make this a non-issue.

**Comment by chachasikes** [comment]
Found the code samples to limit this behavior. Will slate this for 1.1.3 release

**Comment by chachasikes** [comment]
Old, closing, moving notes to new conversations and efforts.
