### ISSUE TITLE
Editor UX: Hitting delete button can accidentally delete blocks

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#206]
We need to think through how to create guardrails around using delete button to delete blocks.

**Comment by chachasikes** [comment]
We can discuss this when we work on the Editor.
- Should check changes for GB for Wordpress 5.8
- Need to look up WordPress community complaints about this issue
- A keystroke listener for 'delete' could be changed to a 'double-delete' (or something) - but this could interfere with the accessibility & keystroke training. which it is in some cases - the issue may be the visual UI and how 'different' the block border outline is - which is what communicates what's selected.

What might be a more transformative option would be to invite some WordPress editors (or find some online lectures) of users using keystroke editors & improve editors keyboard abilities & enhance our understanding of Gutenberg's accessibility features & then recommend some visual improvements as a supplement.

**Comment by chachasikes** [comment]
Support issue but we need to help content team find a way to help train editors with Gutenberg blocks.
