### ISSUE TITLE
Turn on search indexing - Yee

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#207]
Search was returning results pre soft launch and now it doesn't.

**Comment by chachasikes** [comment]
A setting was unchecked on soft launch to prevent google from indexing the site. (though I don't know how it could have indexed a firewalled site?)

Enabling this should make the index work (with the correct domain), though it might also take a couple of days for results to appear. @wrendo

**Comment by wrendo** [comment]
Let's not switch it on until we officially go live.
