### ISSUE TITLE
Editor Bug: Font styles in accordion editor don't match published version

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#208]
![editor-accordion](https://user-images.githubusercontent.com/1387973/123570395-f7e79d00-d77c-11eb-8731-f10ab3ef235c.jpg)

**Comment by chachasikes** [comment]
Good to know... editor is secretly a lot of tiny react apps & has elements that need specific targeting ... (or even unrecommended `!important` tags due to some load order issues between GB & WP.)

**Comment by chachasikes** [comment]
Slating this for next week

**Comment by chachasikes** [comment]
I updated this in upcoming release. The code was disconnected.
We may run into some theme CSS collision issues, but the majorly broken part is fixed now.

**Comment by chachasikes** [comment]
Checking this pre-release - there was an issue with the design system component .plus-minus `margin-top: 8px`

Made it 0px in this version, but we can't totally link to the design system bundle until this is resolved.

**Comment by wrendo** [comment]
Closing this issue as it seems to be resolved.
