### ISSUE TITLE
Bug: Run on words (Safari on Mac, maybe Firefox too)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#216]
see screenshot
![Screen Shot 2021-06-30 at 9 28 48 AM](https://user-images.githubusercontent.com/1387973/124001624-aeb86880-d989-11eb-9c5d-2f79b740358f.png)

**Comment by kkoryaka** [comment]
Fixed now
<img width="706" alt="Screen Shot 2021-09-09 at 9 17 16 AM" src="https://user-images.githubusercontent.com/31669748/132723710-12a88ad5-0c0f-4c5a-bbde-a9431593355b.png">

Please reveiw @wrendo

**Comment by chachasikes** [comment]
Done, closing.
