### ISSUE TITLE
Content bug: Unfinished page alert existing on Contact Us page

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#217]
see screenshot
![Screen Shot 2021-06-30 at 10 23 04 AM](https://user-images.githubusercontent.com/1387973/124008620-787ee700-d991-11eb-8878-dc2c271c66c4.png)

**Comment by m-sullivan7** [comment]
It looks like engineering pushed a code change. This worked yesterday. It's breaking at the point there's a hyperlink in the text. This component should be looked at after launch as I believe the design calls for hyperlinks to work in the alert box.

That said, they also introduced the function that allows you to close the alert box, which isn't appropriate for this alert. I've removed the alert box and replaced with regular paragraph text for this information.
