### ISSUE TITLE
Content bug: Medicinal cannabis page link goes to the wrong place

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#220]
Per DCC:

Medicinal cannabis - first section - last sentence after bullets "where you can use cannabis" - link went to "What's legal and what's not" instead of to "Where you can use cannabis"

**Comment by m-sullivan7** [comment]
There is no anchor link to _Where you can use cannabis_ on the _What's legal_ page. This is a won't fix.
