### ISSUE TITLE
Cosmetic: Page index missing bottom border

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#223]
The last link in the Page Index should have a bottom border:

Current site:
![image](https://user-images.githubusercontent.com/69167298/124653452-4d9e0280-de6b-11eb-8b3a-87d30b2d4403.png)

Figma design: 
![image](https://user-images.githubusercontent.com/69167298/124653525-64dcf000-de6b-11eb-97a6-ff2e81cdca01.png)

**Comment by chachasikes** [comment]
This is something @kkoryaka could work on. The styles are in cagov content-navigation.

**Comment by chachasikes** [comment]
Done, closing.
