### ISSUE TITLE
Design: Incorrect button style

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#224]
The button on the [Search for a licensed business page](https://staginginye.prod3.sites.ca.gov/resources/search-for-licensed-business/) has the wrong style. It should have the same style as the "Learn more" button on the homepage.

Current site:
![image](https://user-images.githubusercontent.com/69167298/124653798-bc7b5b80-de6b-11eb-96c3-0cc3e482e904.png)

Figma design:
![image](https://user-images.githubusercontent.com/69167298/124653848-cd2bd180-de6b-11eb-8509-786ac5b9b4b5.png)

**Comment by adam-little** [comment]
Also on the Track and Trace page: https://staginginye.prod3.sites.ca.gov/licensees/track-and-trace/

**Comment by chachasikes** [comment]
@timothyshambra We did not create button styles for any of our design system sites. Want to create button styles for headless cannabis & then we can migrate the CSS from there to WP cannabis & drought?

**Comment by aaronhans** [comment]
Fix has been merged to headless

Need to implement on WP monolith in different CSS structure to be present in that codebase

**Comment by chachasikes** [comment]
Worked on for Headless.

**Comment by chachasikes** [comment]
Done, closing
