### ISSUE TITLE
Cosmetic: Incorrect spacing of text in homepage hero component

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#225]
h2 line height and spacing between elements do not look correct. There should be 16px spacing between each element. Text line height should follow the guidelines [here](https://github.com/cagov/cannabis.ca.gov/issues/132).

Current site:
![image](https://user-images.githubusercontent.com/69167298/124654636-ca7dac00-de6c-11eb-80c5-d2bf18ceffee.png)

Figma design:
![image](https://user-images.githubusercontent.com/69167298/124654590-ba65cc80-de6c-11eb-923d-e74dcb8cccf9.png)

**Comment by chachasikes** [comment]
Updated for cannabis.ca.gov.
Assigning to @timothyshambra  for updating in cannabis headless.

(Note: The update should already be in place for drought) 

Should live in src/components/hero styles.css
