### ISSUE TITLE
Design: Update hover states for links and buttons

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#227]
See hover state rules below. 

Text links
- Underlined by default
- Remove underline on hover
- Color is "Primary"
- Color on hover is "Primary dark"

Menu links
- Not underlined by default
- Underlined on hover
- Color is "Primary"
- Color on hover is "Primary dark"

Buttons
- Not underlined by default
- Not underlined on hover
- Change button bg color on hover (primary dark)

Card links (i.e. "Get started" links)
- Not underlined by default
- Not underlined on hover
- Change button bg color on hover (Gray 200)

**Comment by aaronhans** [comment]
Assigning to Aaron for now so that the following commits can be moved into the separate component packages:

a3fc006
5b7f6ed
ec0ad61
952c520

These are linked in the last comment in https://github.com/cagov/cannabis.ca.gov/pull/299

Then will remove headless tag, will add WP monolith tag will move ticket back to dev backlog and reassign to new dev

**Comment by aaronhans** [comment]
Updates incorporated into design system elements in this PR: https://github.com/cagov/design-system/pull/51

Also added the missing encoding fix in the content navigation component

**Comment by aaronhans** [comment]
PR to install bumped packages into headless cannabis here: https://github.com/cagov/cannabis.ca.gov/pull/304

**Comment by chachasikes** [comment]
Tagging for publishing to verify if this is done for all sites.

**Comment by aaronhans** [comment]
Review status ok:
- card links are compliant
- button links are compliant

Review status still open:
- links not removing underline on hover
- menu links not changing color on hover

Looks like these CSS fixes got lost in the transition to components in design-system repo.

We can update the design-system base-css and associated components to make them conform. Tagging @adam-little to double check we still want links to remove underline on hover and menu links should change color.

**Comment by adam-little** [comment]
Confirmed! And I just updated the description with a little more detail.

**Comment by chachasikes** [comment]
This sounds done & very old. Closing - feel free to reopen if it's still an issue.
