### ISSUE TITLE
Design: Make page index sticky on scroll

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#234]
On desktop and mobile, the page index should be sticky.

**Comment by kkoryaka** [comment]
@wrendo This one needs JavaScript guru.... (I see tons of on scroll events and multiple condition statements and functionality) Maybe assign it to Carter or Aaron himself. And i can style it and make it look good when all JS is there and functional.

**Comment by chachasikes** [comment]
This wasn't assigned to me, but I could have been tagged on it. Assigning to myself cause this issue got buried.

**Comment by aaronhans** [comment]
Verify we still want to do this

**Comment by adam-little** [comment]
I would still like to do this. I think it will help usability and also be a small step towards introducing more "flair" to the design system. 

@wrendo LMK if you think this is not a priority

**Comment by adam-little** [comment]
Here's a great example of this in action: https://revenuedata.doi.gov/downloads

I love how this version also shows H3's in the page navigation.

**Comment by chachasikes** [comment]
Design decision not reached. 
Closing & it will resurface as a needed and be rescoped.
