### ISSUE TITLE
Design: Homepage "Get started" buttons should be three columns

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#241]
Please make get started buttons 3 columns. For example, if there are 6 buttons then it should be two rows of 3 columns. Currently, it's 4 columns of buttons.

Current: 
![image](https://user-images.githubusercontent.com/69167298/125329155-2768de80-e313-11eb-8214-ddd66b71f5b4.png)

Desired:
![image](https://user-images.githubusercontent.com/69167298/125329287-4e271500-e313-11eb-9220-e0e2078754ac.png)

**Comment by chachasikes** [comment]
This is updated on cannabis.ca.gov, desktop.

**Comment by chachasikes** [comment]
Assigning to @timothyshambra, headless cannabis and drought both need this update.

Source css (in cannabis wordpress site) - width updated to 376px.
If you make any improvements, please ping me & I will add back to our cannabis WP code.

```
.cagov-grid, .cagov-grid .block-editor-block-list__layout {
  display: grid;
  grid-gap: 1.5rem;
}
/* editor override */
.cagov-grid .block-editor-block-list__block {
  margin: 0;
}
@supports (width: min(250px, 100%)) {
  .cagov-grid, .cagov-grid .block-editor-block-list__layout {
    grid-template-columns: repeat(auto-fit, minmax(min(376px, 100%), 1fr));
  }
}
```
