### ISSUE TITLE
Accessibility: Default email launch behavior

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#242]
Per collected feedback: "No email addresses shown on Contact Us page. It launches the mail app instead. This maybe be an issue for those not using the app for mail. Email address is unknown in this case to most. I don’t think everyone knows to hover over it and that the address will show in the lower right corner of their screen."

This is a consideration for all email links. I believe we discussed just typing in the actual email and making those links.

**Comment by m-sullivan7** [comment]
I've updated the page with the email addresses in the body content to make them more visible. I've asked the COVID content team for their opinion on one area of phrasing. I'll wait for their feedback before closing this ticket.

**Comment by m-sullivan7** [comment]
Got team opinion and made updates. This is complete.
