### ISSUE TITLE
Design Maybe: Get started buttons don't feel like buttons

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#245]
This is based on some feedback we've received. However, let's let this lay for a bit for more feedback before committing to any changes. 

Other feedback: Font too large?

**Comment by adam-little** [comment]
I suggest that we wait and see if user feedback corroborates this.

These buttons were based on the design for https://alpha.ca.gov/ which was thoroughly tested. We even added the "arrow" icon to make them feel more actionable.

**Comment by chachasikes** [comment]
This is outdated & will be replaced by new work in Design System, closing.
