### ISSUE TITLE
Discussion: Can the search bar be used to search announcements?

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#246]
This may or may not be a priority item based on user needs. Explore further.

**Comment by chachasikes** [comment]
https://cannabis.ca.gov/sitemap.xml

This is the current sitemap.
It's generated by a plugin: https://www.arnebrachhold.de/projects/wordpress-plugins/google-xml-sitemaps-generator/?utm_source=wp-wm&utm_medium=install&utm_content=plugin-side

Based on how the sitemap tool works (making .xml files with changed files) - don't expect it will ever remove the old page - but click throughs will be taken to the redirected page or the 301 (moved permanently) would be sent to the search engine. The method the WP instances is using is technically correct, but there is another way of doing sitemaps that lists all the pages  - which is more like what we need for headless sites. Not sure what the nature of the prior decisions on this were.

We need an issue for making sitemaps.

**Comment by chachasikes** [comment]
We have another issue about setting up sitemap properly for headless & aside from any curatorial content choices for what's being redirected, the existing site index tells the search engines about the site, so the announcements are coming up in results & picking up any 404s or redirects.

Setting this as "done"
