### ISSUE TITLE
Design: Announcements page - Show only top 5 and paginate the rest + styling considerations

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#249]
Feedback on styling: Maybe color code differences between Announcements, Press Releases, etc.

**Comment by adam-little** [comment]
If the ask is to differentiate the different categories of posts in the Announcements section (i.e. "Press releases" and "Announcements") then I recommend using labels (not colors) which is how we are doing it on the the posts' detail page.

Here's an example. What do you think? cc @m-sullivan7 

![News](https://user-images.githubusercontent.com/69167298/125822102-61c3d391-7589-48de-9d69-e22621c0fed5.png)

**Comment by m-sullivan7** [comment]
I like labeling them. We should be able to pull this from the _Categories_ tag that's already being chosen when a post is created in WordPress. If we used colors, we'd have to provide a key so people understood what they meant.

Stepping back for a moment, is there a user problem we're solving here? Is there a reason that people need to know if something is an announcement versus a press release, or is that an internal designation that doesn't matter to the Californians who come to the site?
