### ISSUE TITLE
Cosmetic: H2 and H3 headers look too similar in size

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#251]
This is per collected feedback

**Comment by adam-little** [comment]
This will be addressed when we update the font sizes as described in this issue here: https://github.com/cagov/cannabis.ca.gov/issues/132

**Comment by adam-little** [comment]
Assigning to @timothyshambra who is helping with https://github.com/cagov/cannabis.ca.gov/issues/132

**Comment by aaronhans** [comment]
Fix for this has been merged to headless

If desired on WP monolith we need to implement there in the totally different CSS structure

**Comment by chachasikes** [comment]
Done, closing.
