### ISSUE TITLE
The Appellations of Origin: Robot Friendly English

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#253]
So are we doing this? :)

**Comment by m-sullivan7** [comment]
My musical talent extends no further than the kazoo...but if we've got [a kazoo solo](https://youtu.be/8ainB6qnWBI?t=55) I think I might be your guy.

**Comment by adam-little** [comment]
While Michael practices his solo, let's start posting cryptic social media messages about a loose collective of anonymous musicians who have been holeding up in an off-the-grid cabin somewhere along the mountainous border region of Humboldt and Mendocino counties. 

For example:

"While hiking in Mendocino I heard the most magical music coming from a grove of redwoods in the valley below. But strangely, there was not a single road nor trail heading anywhere near there. Could it have been...#theappelationsoforigin?"

**Comment by wrendo** [comment]
5 P0

**Comment by wrendo** [comment]
6 Freakin Rad

**Comment by wrendo** [comment]
7 You are all incredible and I am honored to have been able to work with you.
