### ISSUE TITLE
PPF data model changes

### ISSUE THREAD

**Issue by traintestbritt** [cagov/cannabis.ca.gov#256]
Context:
Britt found an open source script that converts JSON into table format in Sheets and applied it **[here](https://docs.google.com/spreadsheets/d/1rAEMZ47rPtXEh40TLDorOskxlqLhz4lQdhVNZPfadlI/edit?usp=sharing)**. The script is automatically shared when the sheet is shared. Go to **Tools** >>  **<> Script editor**

We are using this as our solution to centralize reporting and get PPF data into data studio. There are some requests that can enhance this solution outlined below:

- Removal of these columns: `Time`, `Rid`, `Self`, `Etag`, `Attachments`
- Rename column `TS` to `Timestamp`
- Order the time column for time series analysis
- Change **true/false** values of the `Helpful` column to **yes/no** – we are currently doing this downstream as an intermediate solution so not urgent
- Derive two new columns from the `URL` column: 1) The first column, `Page`, will contain page path level 1 or page path level 1 & 2 if a translated page. 2) The second new column, `Page section`, will contain page path level 2 or page path level 3 if a translated page – we are currently doing this downstream as an intermediate solution so not urgent, see **[report](https://datastudio.google.com/reporting/4dc7f0ec-9b4c-403a-8d16-82909a204760/page/PyCVC)** for example values of these columns
- Rebecca shared this function:  =GOOGLETRANSLATE(cell with text, "source language", "target language") for translations – it won't work downstream, but perhaps there's a transform we can do either in the script or elsewhere? This has not been requested by any end-users/stakeholders and is low priority
- We are requesting to pull 2-3 months of data at a time to avoid sheets row limits

**Comment by aaronhans** [comment]
Also need to add requestor parameter that is defined in the FAAS config outside of the source code, passed in the datastudio reuest and validated before data is returned to give the data some security

**Comment by aaronhans** [comment]
Clarified url splitting requirements to use the path with the translated directory prefix removed if present as the page and any anchor link as pagesection. Also to populate a new attribute: language when on a translated page.

Here is an example of the output from covid with these changes applied:

<img width="693" alt="Screen Shot 2021-07-20 at 6 30 27 PM" src="https://user-images.githubusercontent.com/353360/126416419-3582b7b2-710b-43c0-b407-e606dc5de632.png">

**Comment by aaronhans** [comment]
I am using only last 14 days for covid for now because we get 5K records over the last 90 and that makes the transfer pretty slow

**Comment by aaronhans** [comment]
PR with all the code changes has been updated: https://github.com/cagov/API/pull/52

Will not merge until we get the greenlight from @traintestbritt

**Comment by aaronhans** [comment]
Once code change is deployed these urls will work:

Cannabis: https://api.alpha.ca.gov/FeedbackData/?url=cannabis.ca.gov&requestor=datastudio
Drought: https://api.alpha.ca.gov/FeedbackData/?url=drought.ca.gov&requestor=datastudio
Covid19: https://api.alpha.ca.gov/WasHelpfulData/?url=covid19.ca.gov&requestor=datastudio

The covid19 endpoint has a different initial url because it uses a separate CosmosDB. The covid endpoint is returning 14 days of history by default now because there is so much data it is slow to send the 5K+ records returned in the last 90 days. If it is preferable to deal with the several second delay and receive all 90 days we can change that default param.

**Comment by traintestbritt** [comment]
Thanks for all of these updates/context Aaron!
