### ISSUE TITLE
Headless sitemap

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#257]
https://cannabis.ca.gov/sitemap.xml

This is the current sitemap.
It's generated by a plugin: https://www.arnebrachhold.de/projects/wordpress-plugins/google-xml-sitemaps-generator/?utm_source=wp-wm&utm_medium=install&utm_content=plugin-side

I submitted all the sitemap & subsitemaps to search engines.

Based on how the sitemap tool works (making .xml files with changed files) - don't expect it will ever remove the old page - but click throughs will be taken to the redirected page or the 301 (moved permanently) would be sent to the search engine. 

https://cannabis.ca.gov/sitemap-pt-page-2021-06.xml - this one has most of our changes with a date of change (but not removed pages since we are technically in a new WP instance)

**We will need a headless version of sitemaps.**

Sitemap spec
https://www.w3.org/TR/WCAG20-TECHS/G63.html

For reference:
Our covid19.ca.gov sitemap looks like what I would expect.
https://covid19.ca.gov/sitemap.xml

**Comment by chachasikes** [comment]
cc @wrendo @aaronhans @carterm 

How do we want to manage this?

**Comment by aaronhans** [comment]
@carterm did nice work on the covid sitemaps.

I was planning on adding a nocrawl to the headless version of cannabis because it is going to be up for leaderboard performance comparison but its future is unclear.

**Comment by aaronhans** [comment]
v1 plan:

Use an 11ty template to generate a sitemap file similar to the one on covid that lists all active pages. This can be created with 11ty collections.

**Comment by aaronhans** [comment]
PR https://github.com/cagov/cannabis.ca.gov/pull/367
