### ISSUE TITLE
Cosmetic: Update styling of image captions in WP image block

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#260]
Update styling of caption when adding a caption to an image block in WP.

Current style:
![image](https://user-images.githubusercontent.com/69167298/126197664-8a4e911c-889a-40c0-9660-33bf1ade1e29.png)

Desired style:
![image](https://user-images.githubusercontent.com/69167298/126197736-3cce74a0-f9c3-43fe-92ff-722e6e196e58.png)

[See Figma design](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=11%3A0)

**Comment by chachasikes** [comment]
@wrendo This issue needs a dev owner still

**Comment by chachasikes** [comment]
Unassigning myself for this issue.

@kkoryaka 
As you have probably seen here and there, we have some wp-block styles coming from Gutenberg. 
This caption is one. You should be able to look at the markup generated by WordPress and apply your CSS styles. Putting in the manual CSS is fine - we can do a CSS merge later & I can duplicate into the build code when we are ready.

**Comment by chachasikes** [comment]
Done, closing.
