### ISSUE TITLE
Design: Allow content creators to add captions to image on homepage hero card

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#261]
Currently, content creators can add captions to WP image blocks but not when adding an image to the homepage hero block.

We would like to enable this feature.

In doing so, we need to make additional updates to the layout of the hero block component.

**Proposed design:**
![image](https://user-images.githubusercontent.com/69167298/126201671-8ef1ae5b-3fc5-4d18-a843-00858f096042.png)
![image](https://user-images.githubusercontent.com/69167298/126202633-dc880ba6-974f-4fb4-b924-ce0ae2521e52.png)

- Hero component becomes full width with grey #F9F9FA background
- Hero component no longer has card shape
- Caption is optional

[See Figma](https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/Design-System-Projects?node-id=0%3A1)

**Comment by jaredwyee** [comment]
Thanks @adam-little . @chachasikes @jbum  @aaronhans I assume we will need to provide content designers with the ability to utilize the caption capability based on Adam's design.

Can you consider the appropriate approach and create an issue(s) for the backlog. CA.gov mainboard makes sense as it would be generalized as part of the design system.

Thanks!

**Comment by chachasikes** [comment]
Tagging this one for odi-publishing.

The promotional card & scrollable cards are able to connect to caption data. 
A way to do this is to update the plugin & extend the existing Image block. 

We might even want to make our own Image block that outputs accessible content to our Design System spec.

**Comment by chachasikes** [comment]
Still relevant & needs to be solved. Keeping in our issues queue.
