### ISSUE TITLE
Cosmetic: Closing page alert leaves large gap between header and feature block

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#262]
/Users/conanthelibrarian/Desktop/Screen Shot 2021-07-19 at 11.22.43 AM.png

**Comment by chachasikes** [comment]
Summary of issue:
.cagov-block has regular bottom margin padding for any GB element

When a child webcomponent is closed the padding remains

Need to decide on a way of address this

**Comment by chachasikes** [comment]
(Have a fix for this - will be in next release)
