### ISSUE TITLE
Cannabis client side bundle generation process

### ISSUE THREAD

**Issue by ada-zhou** [cagov/cannabis.ca.gov#263]
Write tests for cannabis client side bundle generation process to verify all included components are there and functional

**Comment by aaronhans** [comment]
This task contains the following large items:

- Define the best way for this bundle to be generated and deployed
  - Needs to have a single command to run that generates the desired bundle
  - Should create a new bundle with versioned url 
  - Should push it somewhere or open PR to deploy it publicly
- Document how this task works in the repo readme


- Figure out the best way to integrate tests on this bundle and the underlying packages
  - Would be cool if the bundle tests triggered a compilation of all the underlying package tests
- Implement the testing plan

**Comment by aaronhans** [comment]
PR: https://github.com/cagov/cannabis.ca.gov/pull/268

**Comment by chachasikes** [comment]
Done, closing.
