### ISSUE TITLE
Editor UX: Saving draft edits for published pages/posts

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#277]
Christina is hoping there's an easy fix for this. She would also like different admin "approver" rights. Is this an existing setting that just needs to be turned on?

**Comment by chachasikes** [comment]
This is something we should talk through & work out for the design system over all. 

We can create an approver role.
We can get a little more understanding of what Christina needs.

This IS something that has many kinds of approval workflows, but they may not all map to what we are doing & how WordPress is managed.

**Comment by chachasikes** [comment]
Update: 

We had some helpful conversations about this. Tagging this issue for odi-publishing because this touchless a lot in our headless publishing system.

**Comment by chachasikes** [comment]
Update: 
Another team is using Oasis plugin

**Comment by chachasikes** [comment]
* Content Admin was already released.
* Moving this to icebox because really this issue is about co-designing a publishing workflow in a more vetted design process.

**Comment by chachasikes** [comment]
This will pick back up but we will have more scope & requirements when we do - so, closing.
