### ISSUE TITLE
Editor Bug: Date field doesn't change in preview mode, but does publish correctly

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#279]
Minor bug

**Comment by chachasikes** [comment]
Which date field?

**Comment by chachasikes** [comment]
Heard this was just a preview weirdness.
@wrendo  do you remember which post?

**Comment by chachasikes** [comment]
UI improvement - adding to a list of items under "Patterns" for team review - not sure it's an issue & no one is currently publishing events with design system, so not a priority yet. Closing.
