### ISSUE TITLE
Update redirects

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#280]
Worked with Christina to sort out the redirects. See notes in the "ip" column. Didn't know where else to put comments as I couldn't add a column for some reason.

https://airtable.com/tblAhvGx6FQxyPJyv/viwe3IF33HVw1fSLI?blocks=hide

**Comment by chachasikes** [comment]
Update:
We have all files.

Will work on this next week. This week is too booked up.

**Comment by chachasikes** [comment]
Closed this out (found a couple of files & sent them to Christina)
