### ISSUE TITLE
add pdf link annotation

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#306]
The pdf links were upgraded to show "pdf" next to them on the monolith here https://github.com/cagov/cannabis.ca.gov/pull/301/files need to incorporate this feature into headless

**Comment by chachasikes** [comment]
This lives in custom JS - is it a component?

**Comment by aaronhans** [comment]
Yes this feature is powered on headless by a design system component @kkoryaka created

Closing
