### ISSUE TITLE
perf upgrade lazy load twitter module on mobile

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#307]
On the mobile version of the cannabis homepage the twitter module is pretty far down the page. This module is a major performance drag. 

Proposal: Change the way this module is loaded to use an interaction observer that retrieves its dependencies when the user scrolls close to it rather than during initial rendering. This will have a big impact on performance on mobile, have no effect on desktop because the module is present immediately there.

**Comment by chachasikes** [comment]
Adding this to QA backlog - we can do some performance optimizations after launch. (Will move this back to icebox if it's not a simple improvement)

**Comment by chachasikes** [comment]
Closing this - we will move to headless where this won't be an issue - and the theme code is likely going to change. 

It would be nice to have a way to register additional JS with the component and have to load in an optimal place in the WordPress page order.
