### ISSUE TITLE
build speed improvement with api fetch cache

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#310]
There is a new feature in 11ty that allows it to cache api call fetch requests recently made in a local build. Enabling this will speed up local rebuilds during development

**Comment by chachasikes** [comment]
Cool!

**Comment by chachasikes** [comment]
Think @xjensen did this. Closing.

**Comment by xjensen** [comment]
I did it in a different way. I didn't use the new 11ty cache feature. Instead, I moved Drought's API requests into wordpress-to-github. Same result: API requests are cached (in the repo).

We might still want to use 11ty's cache feature for non-WP API requests. But if the data is static-y, I think writing it to the repo is a better practice.

**Comment by chachasikes** [comment]
Can we close this - or move it out of the cannabis project somewhere else? @xjensen @aaronhans

**Comment by chachasikes** [comment]
Thank you!!
