### ISSUE TITLE
standardize event tracking

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#314]
The CA Web properties have some custom event tracking implemented in this file: https://github.com/CA-CODE-Works/CAWeb/blob/920640687036df13f643f0613ff3de78f72ec106/assets/js/caweb/AutoTracker.js

Which records event activity in GA:

<img width="666" alt="Screen Shot 2021-08-12 at 4 28 15 PM" src="https://user-images.githubusercontent.com/353360/129284653-84f7afad-6231-4a07-9584-cff31798e44c.png">

Need to consult with @traintestbritt to see if we should mimic this pattern when implementing our event tracking on drought, headless cannabis and on other design system sample sites.

**Comment by traintestbritt** [comment]
I think it's safe for us to keep building on the approach our team has created. I think our approach to creating a category that captures all kinds of clicks rather than having each kind of click be its own category is a better practice.

**Comment by aaronhans** [comment]
Thanks for the guidance @traintestbritt 

Reassigning ticket to me for implementation

**Comment by aaronhans** [comment]
Discussion about event tracking where @traintestbritt posted a training video showing some of this data https://cadotgov.slack.com/archives/C01N25FCCPN/p1631919854012900

We will have a data schism if we change event attribute patterns on headless.

Also should see if the urls of downloadable files match since they are currently relative in the report based on monolith traffic but aren't yet at the same urls on headless (could manage with redirects or change where files are stored by publishing system)

**Comment by aaronhans** [comment]
URLs of downloadable files in headless have been modified to match wordpress locations

**Comment by britt-allen** [comment]
I am not sure I completely understand what's going on, but it seems you spotted and opportunity to clean up our data collection and acted on it without being asked. Thank you for doing so Aaron, you're awesome!

**Comment by aaronhans** [comment]
Thanks for going over the implications of this change with us @britt-allen! 

We will be closing this ticket when we merge the related scroll tracking PR here: https://github.com/cagov/cannabis.ca.gov/pull/393

We can quickly make any event tracking changes requested in separate tickets. We will work on the event logic encapsulation as a reusable component as you recommended. This will be really useful to consolidate code already used on drought, cannabis and covid19 so we can iterate on it in one place: https://github.com/cagov/design-system/issues/108
