### ISSUE TITLE
Navigation drop down link hover color is not from cannabis color theme

### ISSUE THREAD

**Issue by kkoryaka** [cagov/cannabis.ca.gov#319]
Headless drop down link hover color is not from cannabis color theme (probably migrated from drought color theme)
<img width="350" alt="Screen Shot 2021-08-16 at 3 45 29 PM" src="https://user-images.githubusercontent.com/31669748/129638905-507ffb6c-a858-483d-83e2-cedf5cbee54b.png">

**Comment by kkoryaka** [comment]
Can we fix it? Yes, we can,

**Comment by kkoryaka** [comment]
Aaron needs to adjust JavaScript since moving mobile button from navigation to the branding section breaks JS

**Comment by chachasikes** [comment]
Done, closing.
