### ISSUE TITLE
homepage h1

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#333]
The current version of the homepage does not have a visible h1 tag.

The content team weighed in(@m-sullivan7 reviewed this with the rest of the team) and decided that the feature card header should be an h1. It is currently an h2. This change requires an update to the gutenberg block.

**Comment by aaronhans** [comment]
I fear I coded this block in a way that prevents you from being able to fix this @m-sullivan7

Right now the header is its own field and the tag value is hardcoded in the output function.

It sounds like it would be better if this box was more freeform and provided example elements but let authors change them. I'll assign this to @chachasikes to ponder. We might want to make a quick fix to change the tag value so the page has an h1 and then a longer term update to optimize the editing experience on this component.

**Comment by aaronhans** [comment]
I am happy to make the code changes here, this block needs to be changed so that it uses dynamic rendering so that it will be more stable but never got around to that. Assigning the ticket to Chach initially so she can advise on the best approach.

**Comment by m-sullivan7** [comment]
Interesting! Thanks for the background!

**Comment by chachasikes** [comment]
I'll change this for the plugin(s) and manage the code update on migration/update @aaronhans

**Comment by chachasikes** [comment]
New version for drought should already be h2, ported that update to cannabis.

**Comment by chachasikes** [comment]
It should be available in next release (but still has a minor manual data update - which we are progressively restructuring our components to avoid while we develop & iterate with feedback & testing.

**Comment by aaronhans** [comment]
We've got two invisible h1s and no visible h1s on headless.cannabis.ca.gov homepage

One invisible h1 and no visible h1s on cannabis.ca.gov monolith homepage

**Comment by chachasikes** [comment]
Closing, we will review this on headless when we launch.
