### ISSUE TITLE
Sticky behavior of "back to top" button

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#334]
The sticky behavior of this button should match the header behavior described [here](https://github.com/cagov/cannabis.ca.gov/issues/332).

- When scrolling down the page, button should not be visible
- When a user reaches the bottom of the page, it will become visible by sliding in from the side of the page
- When scrolling up the page, it will become visible by sliding in from the side of the page
- When a user stops scrolling up the page, it will remain visible until the user scrolls down the page at which point it slides off the side of the page

**Comment by kkoryaka** [comment]
@adam-little I thought it's already behaves the way you have described in this issue. Do you see any difference the button's current behavior and proposed behavior?

**Comment by adam-little** [comment]
In the proposed behavior, the button does not appear when scrolling _down_ the page. It only appears when a user has reached the bottom of the page, or when a user scrolls _up_ the page.

Currently, the button appears as a user moves _down_ the page.

Additionally, when the button disappears, it should slide right (similar to how it appears by sliding left).

Currently, when the button disappears, there is no animation.
