### ISSUE TITLE
Remove link from "Official website of the State of California" in the statewide header

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#345]
On cannabis.ca.gov, "Official website of the State of California" is a link to the Cannabis homepage.
On headless.ca.gov, it is not a link at all.

Headless.ca.gov (no link) is the preferred behavior here.

**Comment by kkoryaka** [comment]
Unfortunately, that link is part of the CAWEb template....

**Comment by chachasikes** [comment]
Still an issue?

**Comment by adam-little** [comment]
Yes it is. On https://cannabis.ca.gov, "Official website of the State of California" links to the Cannabis homepage. This is not the preferred behavior.

Preferred behavior for the text not to be a link at all, as we have done on https://headless.cannabis.ca.gov/

**Comment by adam-little** [comment]
Based on @kkoryaka's feedback, this link is part of the CAWeb template and can not be changed.
