### ISSUE TITLE
Fix breadcrumb for pages that are not in the main menu

### ISSUE THREAD

**Issue by adam-little** [cagov/cannabis.ca.gov#346]
Noticing that all of the pages on Cannabis that are not linked to from the main menu fail to show the full path in the breadcrumb

Examples:

- https://cannabis.ca.gov/about-us/cannabis-advisory-committee/ [About us > Cannabis Advisory Committee]
- https://cannabis.ca.gov/resources/rulemaking/ [Resources > Rulemaking]
- https://cannabis.ca.gov/about-us/consolidation/ [About us > State cannabis consolidation]

I would argue that these pages should show the full path just as pages in the menu.

**Comment by aaronhans** [comment]
The breadcrumbs on headless are powered by the metadata so are displaying the sections https://headless.cannabis.ca.gov/resources/rulemaking/

**Comment by chachasikes** [comment]
Updated this for headless.

**Comment by chachasikes** [comment]
Added additional support for nested menus. Headless move is coming in next couple of months, closing this.
