### ISSUE TITLE
OG Meta API data for headless

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#354]
Set up og api data & test it for headless (copying from drought.ca.gov)

**Comment by chachasikes** [comment]
New API structure.
* Compiled the login in the plugin & wrote it to a preliminary meta schema that we can normalize for 11ty builds.
* Stored editor informaiton since it's likely that the data fields available will vary by CMS implementation & this is information that benefits from using a UI.

Preview: 
https://dev-cagov-dcc.pantheonsite.io/wp-json/wp/v2/pages/9469

`
og_meta: {
editor: {
platform: "WordPress",
plugin: "autodescription",
plugin_name: "The SEO Framework",
plugin_version: "4.1.5.1",
editor_url: "https://dev-cagov-dcc.pantheonsite.io"
},
site_name: "Department of Cannabis Control",
site_description: "Learn about California cannabis laws and licenses",
site_url: "https://dev-cagov-dcc.pantheonsite.io",
canonical_url: "https://dev-cagov-dcc.pantheonsite.io/?page_id=2",
page_title: "Home page",
page_description: "Learn about California cannabis laws and licenses (excerpt)",
page_social_image_url: "https://dev-cagov-dcc.pantheonsite.io/wp-content/uploads/2021/06/hand-holding-marijuana-leaf-1280x853-503076890-e1493738288674.jpeg",
meta_title: "Department of Cannabis control (Meta title)",
meta_description: "Learn about California laws and licenses (Meta description)",
meta_canonical_url: "http://cannabis.ca.gov/events",
open_graph_title: "Department of Cannabis control (OG title)",
open_graph_description: "Learn about California cannabis laws and licenses (OG Description)",
twitter_title: "Department of Cannabis Control (Twitter title)",
twitter_description: "Learn about California cannabis laws and licenses (Twitter Description)"
},
`

**Comment by aaronhans** [comment]
Removing from the headless cannabis go live milestone because this is no longer a blocker for that step

**Comment by chachasikes** [comment]
Done
