### ISSUE TITLE
Make sure that CA.GOV icon's colors are consistent in header and footer (headless)

### ISSUE THREAD

**Issue by kkoryaka** [cagov/cannabis.ca.gov#361]
Make sure that ca.gov icon is using cagov colors and is consistent in statewide header and statewide footer. 
Also, make sure that "ca.gov home" link in the statewide footer is spelled out and is visible.
<img width="697" alt="Screen Shot 2021-09-14 at 4 42 14 PM" src="https://user-images.githubusercontent.com/31669748/133347995-4f7cfa90-77e7-447c-a897-95e210c59e72.png">
<img width="442" alt="Screen Shot 2021-09-14 at 4 42 06 PM" src="https://user-images.githubusercontent.com/31669748/133348000-bc1cd287-bc64-49ca-8925-ce7d3ccf97ea.png">

**Comment by xjensen** [comment]
@kkoryaka, just FYI, I saw the same problem in Drought, and opened up cagov/design-system#121 to discuss it with Adam. Feel free to pick up that issue if it would help here at Cannabis.

**Comment by chachasikes** [comment]
Done, closing.
