### ISSUE TITLE
repoint cannabis publishing api

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#376]
We want to use api.cannabis.ca.gov once that domain is available and functioning as desired for all cannabis WordPress content consumption requirements.

Related ticket to create new domain: https://github.com/cagov/cannabis.ca.gov/issues/371

We want to get this working ASAP so we can make sure publishing flows properly from a domain that will still be working on the WordPress site after we point production traffic to headless

**Comment by aaronhans** [comment]
This is working now and the domain api.cannabis.ca.gov stays instead of redirecting https://api.cannabis.ca.gov/wp-json/wp/v2/categories

So I think we can change the publishing endpoints now

**Comment by carterm** [comment]
This PR should do the trick...
https://github.com/cagov/cannabis.ca.gov/pull/388
