### ISSUE TITLE
On November 7, correct timings in workflow actions for Daylight Savings switchover.

### ISSUE THREAD

**Issue by jbum** [cagov/cannabis.ca.gov#399]
These two actions are refering to GMT times in their Cron-style timing.

http://cannabis.ca.gov/.github/workflows/e2e-cypress.yml
http://cannabis.ca.gov/.github/workflows/e2e.yml

After the daylight savings switchover on November 7th, they should be advanced an hour (since there will then be an -8 difference instead of a -7 difference to GMT) to correspond to the same local time.

**Comment by chachasikes** [comment]
We made it!
