### ISSUE TITLE
css grid issue `cagov-grid`

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#404]
We have a few problems with `cagov-grid`

1. We have at least three column sizes.
2. Something in one of the grid settings breaks sass compilation.
3. We've declared a global column width that overrides similarly named classes.

**Comment by chachasikes** [comment]
Working in `development-pantheon` branch, which links to content we can edit.

**Comment by chachasikes** [comment]
https://development-pantheon.cannabis.ca.gov.s3-website.us-west-1.amazonaws.com/public-awareness-campaigns
https://development-pantheon.cannabis.ca.gov.s3-website.us-west-1.amazonaws.com/this-is-california-cannabis

`pages/_includes/layouts/index.njk`

This was already causing trouble:
.cagov-grid {
      grid-template-columns: repeat(auto-fit, minmax(min(376px, 100%), 1fr));
}


And `src/components/scrollable-card` and `src/components/promotional-card` are effected.

**Comment by aaronhans** [comment]
The component name change from card-grid to button-grid is in a draft PR that contains all lint and unit tests
