### ISSUE TITLE
Content principles: improve self-serve user research resources

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/cannabis.ca.gov#410]
The second content design principle, [Know your audience and meet them where they are](https://docs.google.com/document/d/1H97lChWT5oACnOd5YzLA1-FB3wwpXpA1tlp5KTajNzU/edit?usp=sharing), includes this section:

> Do not assume you know everything about your audience and what they need. Work with user researchers to understand who your users are and how well they can complete tasks on your website. You may discover audiences and needs you do not know about.
> 
> If possible, test your content with your audience before publishing it. Even if you only talk to one or two people, you can learn things you can use to improve your content.

@clarita1980 left the following comment on this section:

> Audits are a good way to access information about how people perform tasks, also gather info with intercepts and per page feedback to find if there is content- audience fit, user testing sessions. Generative research will help uncover audience needs and complimentary evaluative research will help to make sure you keep meeting their needs.

This ticket is to:

- Discuss resources we can provide to content creators across the state that can be used without user researchers
- Identify useful links we can provide in the content principle itself
- Update the principle documentation with this info

This is a v2 improvement to the content design principles.

**Comment by clarita1980** [comment]
Let's keep it open for now. I am also a bit busy and will start doing interviews next week which it will consume some more of my bandwidth too. Once you are done reach out and we will find a time for sure.

**Comment by abquirarte** [comment]
Thank you for tracking!! Love where this is going.

**Comment by m-sullivan7** [comment]
Clara has put together recommendations on [self-service research options](https://docs.google.com/document/d/1qfijkcpanrtD0cmDDdGrpjJOTcRLYVHBwlH1JWrjr7o/edit#heading=h.bp906otmgm65).

**Comment by m-sullivan7** [comment]
Clara is going to create self-service research recommendations and options as part of a separate project. I'm putting this issue in the icebox and will reactivate when Clara has something that's ready for public consumption we can link to in the content design principles.

**Comment by m-sullivan7** [comment]
I'm going to close this issue as, upon reflection, there won't be much content-side work related to this.
