### ISSUE TITLE
Announcements missing fields on headless

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#418]
As reported during headless site QA (https://docs.google.com/spreadsheets/d/1CqrYdBLG4_1SqP1A75MzebQmYKamqoN_5GomxjsY7fQ/edit#gid=970404558)

Issue:
Announcments should display Category and Date

seen on:
https://headless.cannabis.ca.gov/2021/09/29/department-of-cannabis-controls-proposed-consolidated-cannabis-regulations-are-approved/

If you view the exact same article on the live site, the article has a category and date. These do not appear on headless.

Also incorrect values in the breadcrumbs reported:

When viewing an Announcement or Press Release, there's no link back to the Announcements landing page. Can we make the "Announcements" page in the breadcrumb a link?

Example announcement: https://cannabis.ca.gov/2021/09/15/department-of-cannabis-control-files-emergency-regulations-public-comment-period-begins-today/

When viewing a Press Release, the breadcrumb says "Press Releases" when it should say "Announcements" because the user has arrived from the Announcements page.

Example press release: https://cannabis.ca.gov/2021/09/08/department-of-cannabis-control-proposes-consolidation-of-cannabis-regulations/

Example announcement: https://cannabis.ca.gov/2021/09/15/department-of-cannabis-control-files-emergency-regulations-public-comment-period-begins-today/

**Comment by chachasikes** [comment]
This is resolved & was for headless work
