### ISSUE TITLE
Bug: Dual scroll bars

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#431]
see screenshots

<img width="376" alt="Screen Shot 2021-08-13 at 2 39 38 PM" src="https://user-images.githubusercontent.com/1387973/129421349-fe8fc22e-97fe-4d97-a6ee-34230c27fd16.png">

<img width="494" alt="Screen Shot 2021-08-13 at 2 40 24 PM" src="https://user-images.githubusercontent.com/1387973/129421361-1948af0f-5a13-4542-be4a-19c123e2b7a8.png">

**Comment by xjensen** [comment]
FWIW, I was able to fix this on Drought by removing the optional `data-width` attribute from the embed code that's exported from Twitter.

**Comment by chachasikes** [comment]
Done
