### ISSUE TITLE
License fee equity waiver page

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/cannabis.ca.gov#434]
Create a page that allows people to make a preliminary determination if they are eligible for having their license fee waived through the SB 160 cannabis equity program.

**Comment by m-sullivan7** [comment]
@wrendo Since we're halfway through December and we'd discussed a December 31 due date, I wanted to check in on the priority of this work. Current status is that we sent two drafts to Christina and Eugene.

- [Version that links to a zip code checker site](https://docs.google.com/document/d/1sx6qPbHbs9qytgg7gXJVTBjAqBvmkSoHwrXGAZUGp2Y/edit?usp=sharing)
- [Version that lists the residence requirements, but does not offer people ways to check some of them](https://docs.google.com/document/d/1gXF1f6bzQMF4M7aSsbJR40HfiBJJu7FaHBbzWPFrOeI/edit?usp=sharing)

I haven't seen any feedback from them. How much do we want to follow up with them, especially with end of the year time off?

**Comment by wrendo** [comment]
I'll follow up on this with Christina. I do know she's taking a couple of weeks off for the holidays, so hopefully I can catch her before she leaves.

**Comment by m-sullivan7** [comment]
The page has launched, so closing this issue as done.
