### ISSUE TITLE
Per PR preview sites on AWS for cannabis

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#437]
Work with @xjensen to implement the techniques pioneered here on headless cannabis https://github.com/cagov/odi-engineering/issues/53

**Comment by chachasikes** [comment]
@aaronhans did do this already? 
Adding this one to a list of possible things we may finish for cannabis.

**Comment by aaronhans** [comment]
It doesn't look like this was completed because I don't see helpful comments from the bot with links to the browsable preview environment on the recent PRs.

I wouldn't prioritize this above fixing the performance problems on the live site and only it we are completing the migration to to use the headless site as production

**Comment by zakiya** [comment]
Per @chachasikes on Slack, we don't have the domain.

**Comment by chachasikes** [comment]
Gearing this up for headless.
Here is the Help Desk request.
https://github.com/cagov/Help-Desk/issues/652

This is stuck because I don't have the AWS Certificate values - but have the Cloudfront distribution name on that ticket.

**Comment by chachasikes** [comment]
Done
