### ISSUE TITLE
New cannabis development domain and pull request certificates

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#446]
We have the following DNS records already:
Key: development.cannabis.ca.gov
Value: d2ry7ucz34slea.cloudfront.net

Key: staging.cannabis.ca.gov
Value: d3jzz94ly0m4yu.cloudfront.net

Key: headless.cannabis.ca.gov
Value: d3jn9lsy9jazox.cloudfront.net

We need to make sure that the above domains are all setup in the DCA internal DNS so they resolve for DCC department employees. I know we already did that for headless.cannabis.ca.gov

We need DNS records to get certificates approved for:

Type: CNAME
Key: _100dbd73210b327236c973aa4b0788e3.pr.cannabis.ca.gov.
Value: _77160d9b03fa46eeef0e651205a79f44.vybhcgkthd.acm-validations.aws.

Type: CNAME
Key: _226267db6525263a550aa9dd1d2a3815.development.cannabis.ca.gov.
Value: _076bca4d28c71145b3ff69d758213810.vybhcgkthd.acm-validations.aws.

We have one brand new domain we want to using for live previews of our pull requests:

Type: CNAME
Key: pr.cannabis.ca.gov
Value: d11yq541roz3eo.cloudfront.net

Type: CNAME
Key: *.pr.cannabis.ca.gov
Value: d11yq541roz3eo.cloudfront.net

**Comment by chachasikes** [comment]
Additionally, we need to connect a domain to our editor which will live at 
api.cannabis.ca.gov
api.cannabis.ca.gov is currently pointing at Flywheel, instead we need it to point here:

Type: TXT
Name/Host: _acme-challenge.api.cannabis.ca.gov.
Value: TTlduY5R-vRFOcJkIbKP-MERVYzQVxV6bdsRiut6YDc

https://pantheon.io/docs/guides/launch/configure-dns/

**Comment by wrendo** [comment]
DCA request sent

**Comment by wrendo** [comment]
DCA has completed request

**Comment by aaronhans** [comment]
Thanks @wrendo! I see the AWS certificates have been validated

**Comment by aaronhans** [comment]
Ready to close this

I have the new development service running in Azure, publishing to development branch of the cannabis repo which deploys to the S3 bucket fronted by the CloudFront distro using the new cert and responding at development.cannabis.ca.gov

**Comment by chachasikes** [comment]
Re-opening:
Pantheon is requesting additional values to be added to the DNS

A: 23.185.0.4
AAAA: 2620:12a:8000::4
AAAA: 2620:12a:8001::4

**Comment by chachasikes** [comment]
<img width="782" alt="Screen Shot 2021-12-20 at 5 17 45 PM" src="https://user-images.githubusercontent.com/149436/146854363-d452da80-1974-44ec-a874-d57098a4f5e1.png">

**Comment by wrendo** [comment]
Made a SNOW request. Ticket # CS0041917

**Comment by wrendo** [comment]
SNOW request was fulfilled and the DNS records should be in place.

**Comment by chachasikes** [comment]
All done with this round of requests, closing.
