### ISSUE TITLE
UX Research: Prototype Test #1

### ISSUE THREAD

**Issue by byronsaylors** [cagov/cannabis.ca.gov#45]
- [x] Create a test plan and script
- [ ] Recruit 3-5 participants through CDPH/CHHS for moderated test
- [x] Build screener on UserTesting.com for unmoderated test
- [ ] Conduct user testing
- [ ] Synthesize results

**Comment by abquirarte** [comment]
yay

Angelica Quirarte, "Angie"
Deputy Director | Office of Digital Innovation
c: 916-526-5510 or 916-812-6864
Digital Crisis Standard- covid19.ca.gov
<https://github.com/cagov/covid19/wiki/Crisis-Standard>

Follow us:
Web <https://alpha.ca.gov/> | Blog <https://medium.com/cadotgov> | Twitter
<https://twitter.com/cadotgov>
