### ISSUE TITLE
Add table to supported content in accordions

### ISSUE THREAD

**Issue by m-sullivan7** [cagov/cannabis.ca.gov#459]
We would like to have tables in accordion body content, specifically for use with the _Equity license fee waiver_ page we are developing. This will create a better user experience by allowing people to only look at the information for a handful of counties at one time instead of looking through all of them.

cc: @wrendo for questions about priority

**Comment by m-sullivan7** [comment]
DCC pointed out that we once had the ability to add tables to accordions. We have them on the [Scientific research](https://cannabis.ca.gov/about-us/scientific-research/) page. Looking at the change log might uncover what happened that makes tables an unavailable block in the accordion.

**Comment by chachasikes** [comment]
This is done (1.1.7)
