### ISSUE TITLE
Add side margins to table cells

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#461]
Table cells show side margin when in editor mode, but the preview shows no margins.

Screenshot of editor:
![Screen Shot 2021-12-30 at 6 35 29 PM](https://user-images.githubusercontent.com/1387973/147799808-e60903ad-9efc-434b-9ee8-89b7a68fe112.png)

Screenshot of preview:
![Screen Shot 2021-12-30 at 6 35 22 PM](https://user-images.githubusercontent.com/1387973/147799814-8eba0d32-5fb1-41f6-a976-bd33cee628c9.png)

**Comment by chachasikes** [comment]
Closing as obsolete.

Working on a responsive table, will do a design pass on that new version.
