### ISSUE TITLE
Grid columns not previewing as 3, but 2

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#462]
Any type of grid (card grid, scrollable grid, etc.) shows 3 columns in the editor, but the preview only shows 2 columns.

Screenshot editor:
![Screen Shot 2021-12-30 at 6 39 45 PM](https://user-images.githubusercontent.com/1387973/147799936-d54b8c8b-f225-47df-b912-3e8a698ddb57.png)

Screenshot preview:
![Screen Shot 2021-12-30 at 6 39 54 PM](https://user-images.githubusercontent.com/1387973/147799933-34324da9-5eea-4c03-a600-0a69df69f66c.png)

**Comment by chachasikes** [comment]
Old, closing.
