### ISSUE TITLE
Component: Mailing List (Constant Contact)

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#47]
The word is the cannabis team manages their mailing list with mailchimp and they'd like a signup form on the site.

We need to get the account info, review the mailchimp API and create or embed a signup form into a page on the site.

**Comment by wrendo** [comment]
Let's get all necessary info when we chat with Art/Koji on Wed.

**Comment by wrendo** [comment]
Requested Mailchimp account info from Christina and asked to see how critical it is for this integration to happen now.

**Comment by wrendo** [comment]
Per Christina, we can link the "Sign up for emails" in the footer to here: [https://lp.constantcontactpages.com/su/RVR4SI1/CACannabisDept](https://lp.constantcontactpages.com/su/RVR4SI1/CACannabisDept)

She also wants an inline form somewhere on the Announcements page. Need to sync with Michael and Adam on this.

Here are the CC [quick install guides](http://knowledgebase.constantcontact.com/articles/KnowledgeBase/18053-activating-and-installing-your-sign-up-form) for those code types.
 
Inline Code:

```
<!-- Begin Constant Contact Inline Form Code -->
<div class="ctct-inline-form" data-form-id="ba55d257-840a-417b-a62c-1c3b4a52b9fd"></div>
<!-- End Constant Contact Inline Form Code -->
```
 
Universal Code (used for universal pop-up):

```
<!-- Begin Constant Contact Active Forms -->
<script> var _ctct_m = "1136fdd774ccec37aaeef44776cbf920"; </script>
<script id="signupScript" src="//static.ctctcdn.com/js/signup-form-widget/current/signup-form-widget.min.js" async defer></script>
<!-- End Constant Contact Active Forms -->
```

**Comment by m-sullivan7** [comment]
I've added a text link to https://lp.constantcontactpages.com/su/RVR4SI1/CACannabisDept into the text that will live at the top of the _Announcements_ page. This is loaded into Airtable and ready for importing. Does this move this to done?
