### ISSUE TITLE
For your attention: search.cannabis.ca.gov is down for a few days

### ISSUE THREAD

**Issue by cristiano2lopes** [cagov/cannabis.ca.gov#472]
Hi, you are probably already aware of this issue but [search.cannabis.ca.gov](http://search.cannabis.ca.gov/) has been down for a few days now.
We are a company that provides services to cannabis companies and we use it quite often to provide stakeholders an assurance that a certain business is licensed and show them license details.

Any estimated timeline for it being fixed ? Is it coming back ? 

Thanks for your time and service, on behalf of the [Tymber](https://www.tymber.io/) engineering team:

Cristiano Lopes,
Mobile Software Engineering Lead

<img width="1584" alt="Screenshot 2022-03-14 at 12 25 34" src="https://user-images.githubusercontent.com/1236193/158171696-96e05d8a-6ef7-42b5-a98e-2257f59de062.png">

**Comment by chachasikes** [comment]
Thank you for reporting this [cristiano2lopes](https://github.com/cristiano2lopes) - Have forwarded to the folks who can help.

**Comment by chachasikes** [comment]
Will respond here when we have a confirmation this is resolved.

**Comment by cristiano2lopes** [comment]
@chachasikes I think it's only a problem from people outside of the US (I am connecting from Portugal). With a US connected VPN I can access without any problems.

We use this to send the license info for the Apple App Store Review team and they also can access it (they are probably outside the US also).

Feel free to close it if that is a policy of yours.

**Comment by chachasikes** [comment]
This is good to know. There were some service outages over the last few days, but sounds like your issue is a different issue. 
The team that works on this has received this message and we hope to have a response about this soon.

**Comment by chachasikes** [comment]
@cristiano2lopes 

Thanks for your patience.
We have a recommendation for you.

You can submit an “incident” via CDT’s [Service Now portal](https://services.cdt.ca.gov/csm) to share the pertinent technical details (what systems you previously had access to from Portugal and when that changed).

You can also request confirmation of details as to why something changed.

Here is the link where you can submit the incident request.
https://services.cdt.ca.gov/csm

Thanks for reaching out.

Closing this issue.
