### ISSUE TITLE
Component: Alert (informs DS)

### ISSUE THREAD

**Issue by aaronhans** [cagov/cannabis.ca.gov#49]
There is an alert component in the cannabis site wireframes.

It looks like this could work as a custom Gutenberg block that is added manually to pages when desired.

Konstantin has already created an alert component and a custom Gutenberg block to use it in WordPress.

We should verify this use case then refine the component so that it meets all requirements of new components and is included in the cannabis site testing plan

**Comment by wrendo** [comment]
We need to determine what are launch critical components. To be discussed further.

**Comment by kkoryaka** [comment]
Added alert styles to the custom css to go inline with design system https://github.com/cagov/cannabis.ca.gov/commit/98b2d15ab4403ff3ecd2a8d40ca75dedc0ec312d

**Comment by adam-little** [comment]
Design feedback based on this version of the Alert:
![image](https://user-images.githubusercontent.com/69167298/123479943-a0f09500-d5cf-11eb-9d11-585fc676519e.png)

- Please make icon aligned to first row of text
- Please use megaphone "announcement" icon [see attached svg]
- Figma has "x" link to dismiss alert. This is not a requirement for July 1

[icon.svg.zip](https://github.com/cagov/cannabis.ca.gov/files/6718680/icon.svg.zip)

**Comment by aaronhans** [comment]
This component is live on both WordPress monolith and headless.cannabis.ca.gov

There is an upcoming ticket to migrate the code to the design system: https://github.com/cagov/cannabis.ca.gov/issues/290

Think we should close this now
