### ISSUE TITLE
Enable PR requests on this Github repo

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#496]
Hey @xjensen 

Can you provide instructions on how to set up a PR for this cannabis repo.

Bonus points if the answer is a link to content in our wiki or equivalent!

**Comment by xjensen** [comment]
[PR preview site documentation](https://github.com/cagov/odi-engineering/wiki/Set-up-PR-preview-sites) is available on our [cagov/odi-engineering wiki](https://github.com/cagov/odi-engineering/wiki).
