### ISSUE TITLE
6/13 updates

### ISSUE THREAD

**Issue by zakiya** [cagov/cannabis.ca.gov#508]
From Wes Breazell  via email:

The updated website looks good but we need to update the allow/prohibit percentages on the popup next to the map (see attached). They should match the stats in the two boxes at the top – 47% and 53%, respectively. 

Also, the data for Colusa County and the city of Riverbank in the downloadable spreadsheet need to be updated. Colusa County prohibits all commercial cannabis activity and Riverbank allows distribution and manufacturing (currently listed as prohibiting both). Although the data in the spreadsheet needs to be updated, the data on the website map for both of these jurisdictions is correct.

![Update Stats](https://user-images.githubusercontent.com/915352/173392993-18c1c665-dfd6-479a-a216-dfdef2dab925.PNG)

**Comment by zakiya** [comment]
Replaced file at [api.headles.ca.gov](https://api.cannabis.ca.gov/wp-admin/post.php?action=edit&post=10498&emr_replaced=1) and [cannabis.ca.gov] with [file from main](https://github.com/cagov/cannabis.ca.gov/blob/main/src/js/charts/cannabis-local-ordinances/static/assets/data/cannabis-local-ordinances.2022-02.csv)

**Comment by chachasikes** [comment]
This was already done, closing.
