### ISSUE TITLE
Pagination on announcements page not working

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#511]
The post-list component uses`cagov-pagination` - (in web-component.js) - 

There are two issues:
* recent & current: the pagination button is not working
* mentioned last week in a meeting: possible cache issue - paginator only works up to the ~ 15th item (reported by Wes)

**Comment by chachasikes** [comment]
On test site - it works: https://api.cannabis.ca.gov/about-us/announcements/
UP TO page 12.

**Comment by chachasikes** [comment]
Working now (was NOT clicking forward a little while ago, reported by Yee) - https://cannabis.ca.gov/about-us/announcements/

**Comment by aaronhans** [comment]
Interesting

**Comment by aaronhans** [comment]
There are some inefficiencies inside the pagination component but the big problem in this case is that the parent CAGovPostList component is duplicating the pagination event listener every time posts are retrieved so we get tons of duplicate fetch calls and resulting logic as more pages are retrieved.

Changing the listener applied here https://github.com/cagov/ca-design-system-gutenberg-blocks/blob/main/cagov-patterns/cagov-design-system-posts/blocks/post-list/web-component.js#L105 to only happen inside the above if statement when the pagination component HTML is added to the page the first time fixes the issue

In this file changing lines 96 to 113

```
                    // Set posts content.
                    if(!this.querySelector('.post-list-results')) {
                      this.innerHTML = `<div class="post-list-results"></div>`;
                      if (this.showPagination === true) {
                        this.innerHTML = `<div class="post-list-results"></div><cagov-pagination data-current-page="${this.currentPage}" data-total-pages="${parseInt(itemCount/this.count)}"></cagov-pagination>`
                      }
                      // write the received content into the page along with parent HTML elements and the pagination under the pageable items, also apply the listener to pagination events. This version of content writing only happens on the first page load
                      this.querySelector('.post-list-results').innerHTML = this.template(posts, "wordpress", itemCount);
                      if (this.showPagination === true) { // this is set the first time pagination element is written
                        this.querySelector('cagov-pagination').addEventListener('paginationClick', function (event) {
                          if(event.detail) {
                            this.currentPage = event.detail;
                            this.getWordpressPosts();
                          }
                        }.bind(this), false);
                      }
                    } else {
                      // write the received content into the page, this happens when a visitor clicks to retrieve a subsequent paged set of items
                      this.querySelector('.post-list-results').innerHTML = this.template(posts, "wordpress", itemCount);
                    }
```

I'm not sure if that is the right file to change in the plugin though, [there are a few](https://github.com/cagov/ca-design-system-gutenberg-blocks/search?q=CAGovPostList). I was able to diagnose the issue and test a fix by running the single HTML file locally so would appreciate a little guidance to create a PR

**Comment by chachasikes** [comment]
This is great - Thanks @aaronhans! 

Good question on which file is best & actually loaded, there are a few structures for the patterns left over from a refactor that will all move to a split out custom plugin that is just the more complex pattern codes - need to see which files are redundant. Will let you know.

**Comment by chachasikes** [comment]
Added to release 1.1.7.
https://github.com/cagov/ca-design-system-gutenberg-blocks/releases/tag/1.1.7

Still slow though, could be the API.

We are soon deprecating this version of the site, so closing this. We can reopen if we need to troubleshoot it further.
