### ISSUE TITLE
Upgrade to wp 6.0, CAWebTheme 1.6.3a on flywheel

### ISSUE THREAD

**Issue by zakiya** [cagov/cannabis.ca.gov#512]
Notes:
WordPress 6.0 update seems ok. 
Header is missing after CAWeb theme update

Error at CAWeb Options > Settings 

https://cannabis-ca-gov.lndo.site/wp-admin/admin.php?page=caweb_options

```Fatal error: Uncaught Error: Call to undefined function et_core_cache_has() in /app/wp-content/themes/CAWeb/inc/icon-library.php:39 Stack trace: #0 /app/wp-content/themes/CAWeb/inc/icon-library.php(72): et_pb_get_extended_font_icon_symbols() #1 /app/wp-content/themes/CAWeb/functions.php(477): caweb_symbols(-1, '', '', false) #2 /app/wp-includes/class-wp-hook.php(307): caweb_admin_enqueue_scripts('toplevel_page_c...') #3 /app/wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters(NULL, Array) #4 /app/wp-includes/plugin.php(476): WP_Hook->do_action(Array) #5 /app/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'toplevel_page_c...') #6 /app/wp-admin/admin.php(239): require_once('/app/wp-admin/a...') #7 {main} thrown in /app/wp-content/themes/CAWeb/inc/icon-library.php on line 39```
<img width="953" alt="CleanShot 2022-07-11 at 13 39 06@2x" src="https://user-images.githubusercontent.com/915352/178353995-22457256-7b8d-48f0-979c-da52b67a00df.png">

```appserver_1        | NOTICE: PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function et_core_cache_has() in /app/wp-content/themes/CAWeb/inc/icon-library.php:39
```

**Comment by zakiya** [comment]
- Error resolved by enabling Divi, then CAWeb. Header still missing.

**Comment by zakiya** [comment]
Between CAWeb version 1.6.2 and 1.6.3, /partials/header.php was removed and relocated to /partials/content/header.php and /partials/design-system.php

https://github.com/CA-CODE-Works/CAWeb/commit/e1e20dab7822f53080631d38ac6fb92005372e9d

**Comment by chachasikes** [comment]
This fix was released in 1.1.7
https://github.com/cagov/ca-design-system-gutenberg-blocks/releases/tag/1.1.7

Now that all the backend systems are better synced, and we have multi-dev instances, we can continue testing this.

CDT also has a new QA testing instance where they can try out these updates as well.

Steps to re-test it
- [ ] Enable 1.6.3a CAWeb theme in `flywheel` branch in cannabis-ca-gov Pantheon instance. (Divi 4.17.4)
- [ ] Make sure that release version is 1.1.7 (Pantheon "master" branch is correct)
- [ ] Try this without WordPress 5.9 update to see if it's in the code.
- [ ] Pull Pantheon WP 6.0 code updates.
- [ ] Confirm menu stays.
- [ ] Repeat on CDT QA server.
- [ ] If good, schedule update for main cannabis site with DCC, ODI and CDT - ideally around 3pm M-Th.



We may also need to try this fix with PHP 8.1 and 7.4. 
Production is currently on 7.4.
Our team doesn't currently know when the 8.1 PHP update is coming - but is something to keep in mind.

**Comment by chachasikes** [comment]
Note: I did try this on Pantheon in between some other projects, but needed SFTP mode to be enabled.

**Comment by chachasikes** [comment]
* We updated Pantheon instance to WP 6.0 and already synced latest theme. Closing.
