### ISSUE TITLE
Official website of the State of California - link not correct

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#516]
On cannabis.ca.gov production - the text link doesn't link to ca.gov.
(Reported by Moorea Warren, DCC in meeting)

This issue comes from the WordPress theme. Need to research how this feature is constructed and come up with a recommended fix.

**Comment by chachasikes** [comment]
Diagnosed this issue yesterday.

This is not an issue on headless Design System sites, such as drought.ca.gov.

The message we include is part of the "design system overlay" on top of CAWeb theme. It comes from some CSS that is attached to a "home link" option that is set in CAWeb options.

Note/Reminder: This project was a prototype of creating a design system for the State of California focused on learning & readying CAWeb for incorporating the design system at scale, before the starter components for the Design System existed. The DCC website was created July 2021, primarily focused on content design, merging multiple websites & was built on existing hardware.

The final Design System integration won't work like this. CAWeb is starting to build out the design system version of the CAWeb theme, but that work is not yet complete. Early code is here, but it is not final or production-ready. https://github.com/CA-CODE-Works/CAWeb/tree/master/partials/design-system

This is a non-standard use of something that will ultimately be addressed with a very different mechanism.

Because of this, my recommendation is to apply the fix with the manual JS. https://github.com/cagov/cannabis.ca.gov/tree/main/_monolith/js & alter the CSS
https://github.com/cagov/cannabis.ca.gov/blob/e5e3bc8b5a2b57a2a1dfcb97f0d4783d9b91b70a/_monolith/css/manual-caweb.v1.0.3.css#L84.

Preference would be to include the text inside the element and not in CSS, as CSS text is not translatable.

**Comment by zakiya** [comment]
@xjensen Can you take a look at this one?
