### ISSUE TITLE
Component: Event Page Block (design exists)

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#55]
We need to define, design & scope the types of news post content that will be supported on the DCC cannabis site.

* news post, press-release (assumed)
* news post, event block  (confirm)
* news post, announcement block  (confirm)
* any others?

**Comment by chachasikes** [comment]
When complete, we need to create issues to scope, design, build out these components.

**Comment by wrendo** [comment]
Let's bring Michael into this discussion since he's keyed into incoming content.

**Comment by m-sullivan7** [comment]
For completeness, sharing [the notes from my conversation last week with Christina](https://docs.google.com/document/d/1viLKY2BPJxEKO0MuuoVDTmcQA1FEyU8lqF2BW1wVArA/edit). I believe these answer these questions, but let me know if I'm missing something that will help keep this moving forward.

(Caveat: I don't know what a "block" in the context of a "news post" is. I assume that these are types of things that can be created within a news section. Let me know if I'm wrong!)

- news post, press-release: **yes**. Christina said that right now press releases will be a major aspect of their communications.
- news post, event block: **yes**. While events are not frequent (at most, once a month), they will need to post them and I see the requirements as different from a news release.
- news post, announcement block: **yes**. This would be really similar to the press release, but just have different headers and footers. This [Slack thread](https://cadotgov.slack.com/archives/C01N25FCCPN/p1621441190009000?thread_ts=1621381758.008100&cid=C01N25FCCPN) includes an example of what they consider a press release and what consider an announcement.
- any others? **Not for July 1**, but if we're putting together a post-July 1 roadmap I can ask Christina. The Google Doc has some 

I will confirm these answers with Christina in my end-of-day email to her. She's been pretty good about answering questions like these promptly.

**Comment by wrendo** [comment]
I've repurposed this issue to separate the different concerns. This is now specifically for devs to scope event blocks because we have design for this. I've created a separate issue for design to think through the header/footer differences for press releases vs announcements.

**Comment by chachasikes** [comment]
[Initial spec here](https://github.com/cagov/design-system/issues/14)

Outstanding questions from this issue @wrendo 
* Location data (URL vs... address?)
* How we will handle Add to Calendar 
* Confirm this does not need a header image

**Comment by chachasikes** [comment]
Some updates on this issue:
- Needed more definition for the overall publishing system & data handling (well underway)
- Also needed to clarify this scope in to phases. This is much more complex, even greatly simplified, to make this work correctly.
- We have a simple v1 which is just visual appearance, and I've got a set of data integrations for phase two, which makes the events searchable and filterable for headless. We are very limited in how we can accomplish this and are also deciding patterns for any other content elements that need to operate as entities on the Interwebs, and as sensible data models that can migrate and grow over time.
- The UI integrations all depend on and vary greatly with the CMS editor.

- Updated the CSS
- Finalizing a release to use for the intermediary period.

**Comment by chachasikes** [comment]
More updates on this special component:

* It's part of a pattern.
* Awaiting launch (backed up by headless publishing)
* Headless version being vetted
* A couple of boards for scoping out the underlying data model
* We have a new framework for talking about the publishing system
* Have a team talk planned about content models and the design system (for data patterns like this that need general communication & documentation. Will try same publishing system but with an Airtable Google Calendar to make a super simple event flow & be able to use multiple CMS's but still publish same results.

* Need tests.

**Comment by chachasikes** [comment]
Headless version has other small issues, but shouldn't block just closing this initial request out.

**Comment by chachasikes** [comment]
Shipped. Closing this, it's a duplicate of other events issues. - we need a better system to manage "Patterns"  or doing sprints.
We did ship v1 of events.
