### ISSUE TITLE
Update events content with new layouts (Design exists)

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#56]
After we define the sub-content types for News posts (e.g. press release, event, announcement), we need to:

* Add single select  field in Airtable to set the type
* Tag all the content with the kind of post
* Adjust content importer to generate Gutenberg block code for all the post pages.
* Verify the content comes through (on production)

**Comment by wrendo** [comment]
Let's discuss in our Wed meeting

**Comment by wrendo** [comment]
Repurposing this issue to an active state to apply to event layout. Will create separate issue for press release/announcements.
