### ISSUE TITLE
Decide on URLs: Content Perspective

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#66]
We should sort out naming conventions early on. Needs discussion

**Comment by m-sullivan7** [comment]
Meeting held. [Draft standards created](https://handbook.digital.ca.gov/content/formatting.html#page-urls) based on today's discussion and out to team for feedback before sharing with the cannabis team.

**Comment by m-sullivan7** [comment]
Majority of team has provided input and approved the standards. Additional tickets can be generated if needed. Closing this ticket to reflect today's work.
