### ISSUE TITLE
Design: Press Release vs Announcement

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#70]
Per Cannabis: Press releases and announcements have different headers/footers.

There has been a discussion around labeling announcements as Press Release or Announcement. Per Chach, we can use WP tags.

See this [slack thread](https://cadotgov.slack.com/archives/C01N25FCCPN/p1621441190009000?thread_ts=1621381758.008100&cid=C01N25FCC) for examples of what they consider a press release and what consider an announcement: 

Will confirm this. 

TBD post-launch: label filtering

**Comment by adam-little** [comment]
Let's go with Chach's section. 

In the prototype, the label appears above the title
![image](https://user-images.githubusercontent.com/69167298/121035874-4c9a8800-c77c-11eb-95ed-9c6ba6820695.png)
