### ISSUE TITLE
Design: PDF flow

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#74]
Need to update prototype to show PDF flow for users. 

Per Adam: Using existing approach as Covid site

**Comment by adam-little** [comment]
I have created an icon for PDF links, similar to COVID. Ideally, this icon inherits the same color as link styles (which may vary from agency to agency)

![image](https://user-images.githubusercontent.com/69167298/121249848-0c6a0100-c873-11eb-8c7d-b84e2183542c.png)

https://www.figma.com/file/9FTGOPO5HlsLfYuNrtL9IM/cannabis.ca.gov-screens?node-id=439%3A3287

**Comment by adam-little** [comment]
Assigning to @wrendo to prioritize and assign to engineering

**Comment by kkoryaka** [comment]
@wrendo Please review (pdf icons is now added to the headless): https://headless.cannabis.ca.gov/applicants/application-resources/

**Comment by chachasikes** [comment]
This is done, closing.
