### ISSUE TITLE
Design: File a complaint section

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#76]
This feature page is requested for a post-launch release. Example: https://www.cdph.ca.gov/Programs/CEH/DFDCS/MCSB/Pages/Complaint.aspx

**Comment by m-sullivan7** [comment]
The cannabis team has already created content for a page where you can file a complaint that will have a button that takes people to another site. This content is in final review with them, so nearly finalized.

**Comment by wrendo** [comment]
Need to followup with DCC on this and gauge priority

**Comment by chachasikes** [comment]
@mediajunkie Is this still in scope? If not we can close.
