### ISSUE TITLE
Component: Standard Page Block

### ISSUE THREAD

**Issue by chachasikes** [cagov/cannabis.ca.gov#78]
We also need a Wordpress Gutenberg Block layout that is just a standard page layout that adds the content navigation. A draft of this is already under way.

**Comment by chachasikes** [comment]
[Initial issue spec](https://github.com/cagov/design-system/issues/16)

**Comment by chachasikes** [comment]
V1 is done on our dev site.
Includes 
* Content navigation component
* Content navigation component hidden from main content editor blocks
* Uses a templating system

**Comment by wrendo** [comment]
Waiting on 2nd review by Adam
