### ISSUE TITLE
Plugin Descriptions - 1st Run (week 2 deliverable)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#82]
High priority need so it's not a blocker for Chach. Will schedule a content work session "hackathon".

**Comment by chachasikes** [comment]
* Phase one done
* Set up structure to add more descripitons
* Created Airtable columns to manage/co-write descriptions
* Super helpful
* Appears on hover in GB interface


There are more components we are creating, will need to do another phase two after more development work is done.
