### ISSUE TITLE
Design: Stacked logo for mobile

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#83]
Christina has shared the Dropbox folder with the needed .svg file. I couldn't access the folder. If Adam can't access either, I'll ping Christina to send us the files directly.

**Comment by adam-little** [comment]
Here is the Dropbox folder that I have. It works for me: https://www.dropbox.com/sh/lz7opi6d5f52hwc/AAA2ARIpSvopZMitAZSKtdVYa?dl=0

Attached are the RGB logos.
[Digital (RGB).zip](https://github.com/cagov/cannabis.ca.gov/files/6609823/Digital.RGB.zip)

**Comment by wrendo** [comment]
Direct link to stacked logo .svg: https://www.dropbox.com/sh/lz7opi6d5f52hwc/AADhhb8qgK6f7obQM5ycwXZ6a/Final%20Logo%20Files/Digital%20(RGB)/RGB%20Stacked%20Logo/RGB%20Stacked%20Color?dl=0&subfolder_nav_tracking=1

Per discussion with Adam: 

Stacked logo creates misalignment in mobile design. I need to get clarification from Christina this is still the way they want to go on mobile.

**Comment by adam-little** [comment]
The question for Christina is how important does she think it is to include the fully designed DCC logo (i.e. logo + title).

If it's a requirement, then i recommend we use the horizontal logo on both desktop and mobile.

**Comment by kkoryaka** [comment]
Currently CAWeb theme only provides image logo, which means, the logo text needs to be incorporated into the logo image. There is no separate logo img and separate logo type at this point.

**Comment by adam-little** [comment]
You can use this logo for desktop and mobile. It includes the logo text.
[DCC Logo RGB Horizontal (Color).svg.zip](https://github.com/cagov/cannabis.ca.gov/files/6626341/DCC.Logo.RGB.Horizontal.Color.svg.zip)
