### ISSUE TITLE
Component: Back to top button (WP generated)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#84]
The team discussed and Konstantin brought up the fact that WP has a built in back to top button and we can configure styling

**Comment by adam-little** [comment]
This is not a critical feature, but my understanding is that it was built as a component for COVID, so it should be easy to implement.

The design is in Figma and it has the same behaviors as COVID.

![back to top](https://user-images.githubusercontent.com/69167298/121035157-9c2c8400-c77b-11eb-8d86-3792048b9839.png)
