### ISSUE TITLE
Design: Header (translation links)

### ISSUE THREAD

**Issue by wrendo** [cagov/cannabis.ca.gov#88]
How does this need to look if using Google translate buttons?

**Comment by adam-little** [comment]
@kkoryaka This is looking good.

Are you able to customize it further? For example, changing the text label and removing the container shape?

It would be great to aim for something like these, where all links have a uniform look:
![image](https://user-images.githubusercontent.com/69167298/121418872-60d7b400-c939-11eb-8abc-b04ad2cd3243.png)

**Comment by adam-little** [comment]
Please also note that our designs say "Official website of the State of California"

**Comment by adam-little** [comment]
As per @wrendo's comment in Slack, let's remove the Settings option for now.
