### ISSUE TITLE
Android Compatibility Issue with Mobile Search Toggle Button

### ISSUE THREAD

**Issue by mukhtaramukhtar** [cagov/cannabis.ca.gov#9509]
I've observed that on Android mobile devices, the search button doesn't activate the search field display for cannabis.ca.gov. I noticed the same issue persists on drought.ca.gov

**Comment by jbum** [comment]
@mukhtaramukhtar I've been able to reproduce this using BrowserStack on several phones, both in Chrome and Firefox browsers.  What I'm seeing is that when you click on the search icon (magnifying glass), the search box briefly appears, and then gets immediately dismissed.  Is that also what you are seeing?

**Comment by mukhtaramukhtar** [comment]
@jbum yes, exactly.
